- CONTRIBUTING.md
- install-publisher.bash
Updates the `install-publisher.bash` script as part of the release of `v1.1.0`
> Update install-publisher script version

- CHANGELOG.md
- docs/installation.md
- extensions/vscode/CHANGELOG.md
This PR updates the changelog in preparation for v1.1.3.
> Update changelog for v1.1.3

- extensions/vscode/scripts/set-version.py
When we build a release package in CI (on a tag), our scripts update the version number in the extension's `package.json`. This PR limits this action to only happen when the `CI` environment variable is `true`, so it won't happen locally.
> Only update version in package.json in CI

- extensions/vscode/src/views/configurations.ts
- extensions/vscode/src/views/contentRecords.ts
This PR does a few things:
- Adds a description to Configurations and Deployments in their respective views based on the `projectDir`
- If the `projectDir` is not `.` then the `projectDir` is the description
- Adjusts the delete for both to pass the `projectDir` using the `dir` query param so deletion will work for recursively listed Configurations and Deployments
Part of #1845
> Use projectDir in config and content record views

- test/README.md
Just adding docs for bats and pending vscode-ui tests.
> Add docs for tests

- extensions/vscode/src/utils/files.ts
- extensions/vscode/src/utils/names.ts
- extensions/vscode/src/views/configurations.ts
Resolves #1383 
Updated filename validation utility method.
The places you can supply a filename are:
- Within the Configurations View:
- right-click: clone
- right-click: rename
- Within the Deployments View:
- right-click: rename 
Try these operations and make sure you see an error when supplying a name of all blanks. Also, confirm valid filename is accepted.
> Disallow file names which are all blanks

- internal/services/api/get_deployments.go
- internal/services/api/get_deployments_test.go
This PR implements a recursive option to the GET /api/deployments endpoint.
Part of https://github.com/posit-dev/publisher/issues/1850
Walk the tree looking for .posit directories; when one is found, list configurations from the parent directory. The built-in exclusions are applied to avoid excess directory traversals.
Added tests for the recursive flag.
```
curl -s localhost:9001/api/deployments?recursive=true | jq
curl -s 'localhost:9001/api/deployments?recursive=true&dir=test/sample-content/fastapi-simple' | jq
curl -s 'localhost:9001/api/deployments?recursive=true&dir=test&entrypoint=simple.py' | jq
```
> Recursive deployments API

- internal/bundles/matcher/walker.go
This PR adds `node_modules` as a built-in exclusion. 
Follow-on to #1929.
> Exclude node_modules

- extensions/vscode/src/api/resources/ContentRecords.ts
> Add recursive param support to Deployments getAll

- extensions/vscode/src/views/configurations.ts
- extensions/vscode/src/views/contentRecords.ts
Shows all Configurations and Deployments in their respective views.
Note that without the fix in #1938 you will get an error if you have no Configurations or Deployments.
Part of #1843 and the Nested Folder work in #1849 (although this is outside of the home view, but will help with debugging)
> Recursively fetch configs and deployments in views

- extensions/vscode/src/utils/webviewConduit.ts
- extensions/vscode/src/views/configurations.ts
- extensions/vscode/src/views/contentRecords.ts
- extensions/vscode/src/views/credentials.ts
- extensions/vscode/src/views/helpAndFeedback.ts
- extensions/vscode/src/views/homeView.ts
- extensions/vscode/src/views/logs.ts
- extensions/vscode/src/views/project.ts
- extensions/vscode/webviews/homeView/src/HostConduitService.ts
resolves #1497 
resolves #1942 
Simple refactoring of private variable names and part of a switch statement.
A simple sanity check is all that is needed. 
I will be building more functionality on top of this branch, so if there are any issues, I think I should encounter them myself.
> Refactor underscore private names and onConduitMsg switch statement

- extensions/vscode/src/api/client.ts
- extensions/vscode/src/bus.ts
- extensions/vscode/src/events.ts
- extensions/vscode/src/multiStepInputs/newConfig.ts
- extensions/vscode/src/multiStepInputs/newCredential.ts
- extensions/vscode/src/multiStepInputs/newDeployment.ts
- extensions/vscode/src/multiStepInputs/selectConfig.ts
- extensions/vscode/src/utils/progress.ts
- extensions/vscode/src/utils/webviewConduit.ts
- extensions/vscode/src/views/configurations.ts
- extensions/vscode/src/views/contentRecords.ts
- extensions/vscode/src/views/homeView.ts
We need visibility into performance issues when the extension is running within VSCode that has opened a large folder full of files and other folders.
This PR instruments the API calls and the progress windows to expose how long some of these operations are displaying to the users, so that we can analyze and optimize the underlying code.
I have organized my changes within individual commits, listed below.
- disable noisy bus and event traces
- Implement duration tracing for axios calls
- implement showProgress utility, with duration tracing
- use new showProgress utility rather than window.withProgress
I plan to come back and allow all of this tracing to be configurable …
> Instrument vscode progress and api calls

- .prettierignore
Resolves #1947 
Skip the sample content files. 
Run `just format` and make sure no files are listed from the `test/sample-content` subdirectories.
> Add additional directories to be ignored by prettier

- extensions/vscode/src/types/messages/webviewToHostMessages.ts
- extensions/vscode/src/views/homeView.ts
- extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
Resolves #1964 
We have the full path to the configuration file. This is sufficient to be used to open the correct file.
Open the Sample output directory within VSCode
1. Create a deployment for multi-type project
2. Create a deployment for fastapi-simple project
3. Select your multi-type project, click the edit icon to edit it. Confirm the correct file is opened
4. Repeat for the fastapi-simple project and confirm the correct file is opened.
> Wrong config opened - multi-folder compatible location not used

- extensions/vscode/src/views/homeView.ts
> Use HomeViewState type for selection state

- extensions/vscode/src/views/homeView.ts
> Improve param name for deployment selection

- extensions/vscode/package.json
- extensions/vscode/src/extension.ts
This PR changes the activation events from `workspaceContains:*` to `workspaceContains:/`. The former requires a file to exist; the latter does not.
Fixes #1991 
Open an empty folder; a folder containing only a folder; and a folder containing files. The extension icon should always show up.
> Always activate the extension

- extensions/vscode/src/api/resources/Configurations.ts
- extensions/vscode/src/api/resources/ContentRecords.ts
- extensions/vscode/src/api/resources/Files.ts
- extensions/vscode/src/api/resources/Packages.ts
- extensions/vscode/src/entrypointTracker.ts
- extensions/vscode/src/multiStepInputs/newConfig.ts
- extensions/vscode/src/multiStepInputs/newDeployment.ts
- extensions/vscode/src/multiStepInputs/selectConfig.ts
- extensions/vscode/src/utils/names.ts
- extensions/vscode/src/views/configurations.ts
- extensions/vscode/src/views/contentRecords.ts
- extensions/vscode/src/views/homeView.ts
resolves: #2000 
partial: #1973 
Change Client API code to make directory required and optional params moved back to last parameter of API, when needed.
General regression, since almost all APIs have changed. Most of them are supported by the language, but some have strings swapped for strings...
> Move dir out of params and make required in API signatures

- extensions/vscode/package-lock.json
- extensions/vscode/package.json
This PR changes the dev version number to 99.99.99, so that dev versions will never be auto-"updated" to a marketplace version.
Build the VSIX and install locally. Reload the window, check extension updates, etc. The Publisher should not be updated.
> Make dev versions always the latest

- extensions/vscode/src/multiStepInputs/selectNewOrExistingConfig.ts
- extensions/vscode/src/views/homeView.ts
Resolves #2007 
file rename and method rename.
> Refactor: Rename file and method - selectConfig

- CHANGELOG.md
- extensions/vscode/CHANGELOG.md
This PR adds details for beta to the CHANGELOG
It updates the root level changelog, and the one included in the VSCode extension.
Part of #1967
I left out code refactors like we normally do, but also didn't include fixes to bugs / regressions caused during Beta 4 development.
> Add changelog for beta 4

- docs/installation.md
- docs/vscode.md
- install-publisher.bash
Beta 4 🎉 
This should contain the last of what we need to update to tag `1.1.4`
Resolves #1967
> Beta 4 documentation and script updates

- .github/workflows/contract.yaml
- test/setup/connect_setup.py
- test/vscode-ui/test/specs/extension.spec.ts
Removes the Config check in the UI tests.  I also noticed some flakiness caused by the location of my fuzzbucket ssh key I create in GH Actions, I moved that to a shared location so other tests can access it.
> Remove Config check in UI tests

- internal/inspect/detectors/notebook.go
- internal/inspect/detectors/notebook_test.go
Fixes #2036
Detect when the JSON decoder returns io.EOF. Ignore the error, and don't return a configuration for this entrypoint (since an empty notebook file cannot be deployed).
Added a unit test.
Open the sample-content directory and add a deployment (there's an empty notebook file in there).
> Handle empty notebook files

- internal/inspect/detectors/pyshiny.go
- internal/inspect/detectors/pyshiny_test.go
Fixes #2011
Continue checking potential entrypoints, even if one of them is not a PyShiny app.
Added a test for this case.
Clone https://github.com/posit-dev/posit-conf-survey and inspect it (using the old recursive inspection).
> Continue checking if a non-PyShiny file is found

- internal/credentials/credentials.go
- internal/credentials/credentials_test.go
This PR implements a read-only single-credential file for use with Workbench until we can get full credential persistence. It replaces to environment variable method, since they are not available when workbench VSCode sessions start up.
Fixes #2088 
Read a file instead of environment variables.
Updated the existing tests.
Create ~/.connect-credentials with a format like
```
url = 'https://rsc.radixu.com/'
key = 'n4Dm9V7or0bUkyvD6Q4l4dcY1eNDEqZs'
```
> Switch from env vars to file credentials

- CHANGELOG.md
- docs/installation.md
- docs/vscode.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
This PR includes changes to the CHANGELOGs, scripts, and documentation for the `1.1.5` release.
> Documentation and Changelog for 1.1.5 release

- extensions/vscode/src/utils/errors.ts
- internal/services/api/api_helpers.go
This PR returns backend error text as the body of responses with status 500 so that it can be displayed to the user instead of `Internal Server Error`.
Fixes #2094
This isn't currently covered by tests.
Create an error that will result in a 500, for example see the linked issue (I tested by injecting an error in the backend).
> Return error text with 500 responses

- extensions/vscode/src/utils/files.ts
Resolves: #2103 
1. Activate the extensions interface, and click on one of them so that their description page is shown
2. Activate the publisher extension, then hit the plus sign
Validate that the New Deployment entry point pick list displays, without error.
> Bug fix: where tab is non-text (with no input attribute)

- extensions/vscode/src/multiStepInputs/newDeployment.ts
- extensions/vscode/src/state.ts
- extensions/vscode/src/utils/errors.ts
- extensions/vscode/src/views/homeView.ts
Resolves #2116 
Code usage of entrypoint variables were confusing as to what form was needed for correct functionality. They exists in multiple forms: an absolute URI, a relative path to the entrypoint, the name of the entrypoint file itself, and the project dir for the entrypoint. To resolve this, I have made the variables names more explicit as they are used and passed around.
I've also included a comment correction in this PR, which was discovered as I debugged why the inspection API was not silently suppressing the API error of 404, when the file was not found. The fix to get the code from the response was required to get this bug fixed.
Reproduce the steps listed …
> Fix entrypoint publishing bug

- cmd/publisher/commands/requirements_create.go
- cmd/publisher/commands/requirements_show.go
- extensions/vscode/src/api/resources/Packages.ts
- extensions/vscode/src/api/types/packages.ts
- extensions/vscode/src/views/homeView.ts
- internal/inspect/python.go
- internal/inspect/python_mock.go
- internal/inspect/python_test.go
- internal/services/api/post_packages_python_scan.go
- internal/services/api/post_packages_python_scan_test.go
This PR warns users when Python package scanning can't find one or more packages in the local library. 
Fixes #2113
A better alternative to #2115
The package scanner returns a list of package specs, as well as a list of packages that were not found. The frontend warns the user if there are packages that couldn't be found.
Updated existing unit test in the backend.
Add an import that of a package that isn't installed locally, then run the package scanner. You should see a warning message with instructions on how to resolve it.
> Warn about packages not found during scanning

- go.mod
Fixes #2129 
Existing tests should pass.
Smoke test.
> Update to go 1.23

- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- extensions/vscode/webviews/homeView/package-lock.json
- extensions/vscode/webviews/homeView/package.json
Upgrades Axios to the latest version in the extension and the home view.
Resolves #2138
> Upgrade axios package

- extensions/vscode/package-lock.json
- extensions/vscode/webviews/homeView/package-lock.json
This is a follow-up to #2140 that just upgrades our npm dependencies with `npm upgrade`
> Upgrade npm dependencies

- extensions/vscode/.eslintrc.json
- extensions/vscode/src/api/types/events.ts
- extensions/vscode/src/events.ts
- extensions/vscode/src/multiStepInputs/multiStepHelper.ts
- extensions/vscode/src/multiStepInputs/newCredential.ts
- extensions/vscode/src/multiStepInputs/newDeployment.ts
- extensions/vscode/src/utils/webviewConduit.ts
- extensions/vscode/src/views/homeView.ts
resolves #1912 
Added eslint rule: `no-restricted-syntax` specifying `ThrowStatement` as the AST selector.
Then I cleaned up the errors, mostly with `showErrorMessage` calls showing an "Internal Error".
The errors found were:
```
~/dev/publishing-client/extensions/vscode sagerb-remove-unnecessary-async-expressions > npm run lint
> publisher@99.0.0 lint
> eslint src --ext ts --max-warnings 0
/Users/billsager/dev/publishing-client/extensions/vscode/src/events.ts
234:11  error  Using 'ThrowStatement' is not allowed  no-restricted-syntax
269:11  error  Using 'ThrowStatement' is not allowed  no-restricted-syntax
/Users/billsager/dev/publishing-client/extensions/vscode/src/mul …
```
> Eliminate throws for internal errors

- extensions/vscode/webviews/homeView/src/components/views/HelpAndFeedback.vue
Fixes an issue after rebasing and merging #2150 where the imports were bad.
> Fix imports in HelpAndFeedback

- internal/services/api/api_helpers.go
PR #2095 added the error text to 500 responses from the backend to provide more informative error messaging. Error messages may contain contents from the request, such as the request URL. This introduces a potential XSS vulnerability, as reported by Snyk.
This PR sanitizes the error messages.
> Escape errors rendered by InternalError

- go.mod
- go.sum
- vendor/golang.org/x/sys/LICENSE
- vendor/golang.org/x/sys/windows/security_windows.go
- vendor/golang.org/x/sys/windows/syscall_windows.go
- vendor/golang.org/x/sys/windows/types_windows.go
- vendor/golang.org/x/sys/windows/zsyscall_windows.go
- vendor/golang.org/x/text/LICENSE
- vendor/modules.txt
This PR updates the go `crypto` package to the latest version, avoiding a [CVE](https://www.cve.org/CVERecord?id=CVE-2022-30636) present in versions <= 0.23.0.
Existing tests should pass.
> Update to go-crypto 0.26.0

- extensions/vscode/src/constants.ts
Just cleaning up an unused const.
> Remove unused ContentRecords view const

- test/bats/contract/deploy.bats
- test/vscode-ui/test/specs/fastapi.spec.ts
- test/vscode-ui/test/specs/nested-fastapi.spec.ts
Add new lines to the expected config output. Test needs updating after this change: https://github.com/posit-dev/publisher/pull/2163
> fix tests for new line file array

- extensions/vscode/src/extension.ts
- extensions/vscode/src/views/homeView.ts
Resolves #2180 
I removed the calls to initiate publishing but maintained the logic for selecting or prompts which were involved in selecting the applicable deployment for the entrypoint file.
For a given entrypoint file:
- if there are no deployments which are created for that entrypoint file, a new deployment flow will be initiated
- if there is only one existing deployment for that entrypoint file, it should be selected
- if there are multiple, then selection between the multiple should be initiated
> Remove automatic deployment from entrypoint initiated publish icon

- CHANGELOG.md
- docs/installation.md
- docs/licenses.md
- docs/vscode.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
This PR preps us for the release of `1.1.6` by:
- Updating the scripts to point to `1.1.6`
- Adds details for the release into the changelog
- Adds additional licenses
- Updates our VS Code Extension documentation
Resolves #2196
Resolves #2214
> Update scripts and docs for 1.1.6

- .github/CODEOWNERS
Updating CODEOWNERS to match my current bandwidth.
I noticed I couldn't keep up with all messages, but I would like to keep up with the changes in internal.
> chore: move @tdstein as codeowner from * to internal

- CONTRIBUTING.md
This PR adds a few small notes to our `CONTRIBUTING.md` doc about how we manage (Content Record and Configuration) schema updates.
> Add notes to CONTRIBUTING about schema updates

- extensions/vscode/package.json
Resolves #2209 
The tool tip changed from: `Deploy with this Entrypoint` to `Deploy with Posit Publisher`. This is visible when you hover over the publisher icon when an entrypoint file is active within VSCode.
> Change tooltip for entrypoint file action

- extensions/vscode/src/types/messages/hostToWebviewMessages.ts
- extensions/vscode/src/views/homeView.ts
- extensions/vscode/webviews/homeView/package-lock.json
- extensions/vscode/webviews/homeView/package.json
- extensions/vscode/webviews/homeView/src/HostConduitService.ts
- extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
- extensions/vscode/webviews/homeView/src/components/QuickPickItem.vue
- extensions/vscode/webviews/homeView/src/stores/home.ts
- extensions/vscode/webviews/homeView/vite.config.ts
Resolves #2248 
With this change, the entrypoint is now shown on the button displaying the current selected deployment as well as within the quick pick list of available deployments, as seen below:
Simply build and verify new functionality is displayed.
> Update QuickPickItem and EvenEasierDeploy to show entrypoint more prominently.

- extensions/vscode/webviews/homeView/src/App.vue
…figuration
resolves #2309 
Simply pulled the treeViews out of the `v-if` that was checking for a selected deployment.
Deletion of existing deployments/configs when have been last selected will trigger this as well as an initial state where you're opening up a directory which has not yet had a deployment selected.
> Always show credentials and help sections

- docs/installation.md
Adds inotify instructions to docs for linux users.
> inotify doc udpate

- .github/workflows/contract.yaml
- .github/workflows/vscode-ui.yaml
- test/vscode-ui/wdio.conf.ts
VSCode UI tests started failing when VSCode updated to 1.94.1 which broke the webdriver integration.  The error seemed to point to chromedriver, so I decided to add a chromedriver installation in GHActions and it worked!
> Install chromedriver in CI

- test/vscode-ui/package-lock.json
updates package-lock for dependabot PRs:
https://github.com/posit-dev/publisher/pull/2172
https://github.com/posit-dev/publisher/pull/2367
> Dependabot Updates for VSCode UI tests

- test/sample-content/stock-report-jupyter/requirements.txt
updates jupyter notebook requirement for dependabot PR: 
https://github.com/posit-dev/publisher/pull/2220
> Dependabot Update for Jupyter Notebook sample content

- extensions/vscode/src/eventErrors.test.ts
- extensions/vscode/src/eventErrors.ts
- internal/clients/connect/apptypes.go
- internal/clients/connect/capabilities.go
- internal/clients/connect/client_connect.go
- internal/clients/connect/client_connect_test.go
- internal/clients/connect/content.go
- internal/events/error_codes.go
Resolves #2301
This PR adds a appMode pre-flight check, so a content item selected by mistake with the wrong appMode doesn't get updated.
Additional pre-flight check added. It now shows in the Publisher log and the error displays consistently.
Unit tests updated.
To reproduce the issue, (and not have to deal with selectively updating your config manually), you should create a new deployment and then associate it with a different appMode type of content already deployed.
Please also verify that normal re-deployment works without an issue.
> Add content type preflight check for already deployed content

- extensions/vscode/src/multiStepInputs/newDeployment.ts
Resolves #2386 
Updated to a simpler message:
Create a new deployment, pick the file explorer, and pick a file outside of the workspace. You should see the error and confirm the new shorter message.
> Update out of workspace error message

- extensions/vscode/README.md
Broke this off from #2352 easier review. This adds gifs to the different feature sections to highlight them:
- "Start in VS Code or Positron and end with content on Posit Connect"
- Shows the flow of creating a deployment, reviewing it, and sending it up
- "Deployment logs"
- Shows the Deployment logs through a deployment
Part of #2024
> Add gifs to feature sections in extension README

- CHANGELOG.md
- docs/installation.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
Changes needed ahead of publishing release 1.2.1, made following instructions present in `CONTRIBUTING.md`
> Release 1.2.1 PR

- .github/workflows/contract.yaml
- test/scripts/test-runner.bash
- test/setup/connect_setup.py
- test/setup/get_ip.py
Update to Python 3.13 and fix some fuzzbucket issues.
MacOS in Github Actions only works with the current latest python version.  Although we're using `setup-python` to set the python version to 3.12, it only sets the current shell to 3.12.  VSCode launches a new shell and gets the system default (3.13).  Whenever Github decides to update the default version, we'll have to update the workflow to use it.  We'll also need to update the fuzzbucket image to use the most current python version.
This PR uses 3.13 for the VSCode UI tests, but it cannot use 3.13 for the CLI deployment tests as there are packages that are not yet compatible with 3.13.
This also attempts to fix some of the flake we see nightly with fuzzbucket. I added a separate, simplified script that just gets the IP Address of …
> Nightly VSCode UI Tests: Upgrade to Python 3.13

- go.mod
Upgrades our Go version to the latest version `1.23.3`
Resolves #2427 
> Upgrade to Go 1.23.3

- .github/pull_request_template.md
Very simple PR that adds a User Impact section to our PR template.
> Add user impact section to PR template

- CONTRIBUTING.md
This PR adds a section to CONTRIBUTING.md describing how to push updated schemas to the CDN.
This process could be automated in the future, but it is currently manual.
cc @sagerb 
> Document how to publish updated schemas to the CDN

- test/vscode-ui/package-lock.json
Ran `npm update` to update dependencies in our `/test/vscode-ui` package.
Also captures #2172 and #2444
> Update test/vscode-ui dependencies

- extensions/vscode/webviews/homeView/package-lock.json
This updates the dependencies for the home webview. This takes care of #2490
> Update home webview dependencies

- docs/vscode.md
Missed adding a screenshot to this section prior to merging #2507. Oops, here it is now 🎉
> Add image in vscode doc under first time deploying

- CHANGELOG.md
- docs/installation.md
- docs/licenses.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
This PR sets up the release of `1.10.0`:
- Updates the documentation and install script to point to `1.10.0`
- Checks for license updates (there were some this time)
- Updates the CHANGELOGs for `1.10.0`
> 1.10.0 Release

- extensions/vscode/package-lock.json
- extensions/vscode/webviews/homeView/package-lock.json
Upgrades the dependencies for the extension and the home view to address the Vitest Remote Code Execution CVE.
> Upgrade extension dependencies

- CONTRIBUTING.md
Added small section `Committing Changes to the repo`, which indicates that you must have performed an `npm install` on both the root of the repo as well as the `test/e2e` subdirectory, in order to pass the pre-commit hook.
Other changes were included and made automatically, as the sections were not present (so the TOC was cleaned up).
No impact to customer or product. Development notes only.
> Simple update to CONTRIBUTING.md 

- extensions/vscode/package-lock.json
- extensions/vscode/webviews/homeView/package-lock.json
- package-lock.json
Runs `npm upgrade` in our three packages.
Mainly addresses the `vite` bump from #2619
> Run npm upgrade across repo

- CHANGELOG.md
- docs/installation.md
- docs/licenses.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
Preparing for Publisher Release 1.12.0
Followed instructions within `/CONTRIBUTING.md` section `Before Releasing`
> Release 1.12.0 prep

- CHANGELOG.md
- docs/installation.md
- docs/licenses.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
Prep for Publisher Release 1.14.0
> Release 1.14.0

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- docs/troubleshooting.md
It'd be good to have better guidance when reporting bugs or feature requests with new issue templates.
> Bug and feature GH issue templates

- CHANGELOG.md
- docs/installation.md
- docs/licenses.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
> release 1.16.0

- CONTRIBUTING.md
Add marketplace links to the release doc and guidance for how to confirm a release was successfully published.
doc update
developer only
n/a
make sure I write good
> update release doc with instructions to inspect registries

- CHANGELOG.md
- docs/installation.md
- docs/licenses.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
This PR sets up a release for `1.16.1`.
I did have some license updates I assume from frontend dependencies changing, by the looks of it.
> Release `1.16.1`

- CHANGELOG.md
- cmd/publisher/commands/ui.go
- cmd/publisher/commands/ui_test.go
- cmd/publisher/main.go
- extensions/vscode/CHANGELOG.md
- internal/cli_types/base.go
- internal/cli_types/base_test.go
Resolves #2697 
An account list was being created before the keychain setting was resolved, which could lead to incorrect behavior if the keychain was not enabled. The account list should be created after the keychain setting is determined.
This PR ensures the account list is initialized only after the keychain setting is resolved.
- Removed the obsolete Accounts field from CLIContext and its constructor signature.
- Moved accounts.NewAccountList call from main.go into UICmd.Run after UseKeychain is set.
- Updated changelogs in both root and VSCode extension to document the fix.
This change fixes a bug, that would mostly affect developers as they test the different …
> Fix issue with account list initialization not using the keychain setting

- internal/services/api/get_connect_cloud_accounts.go
- internal/services/api/get_connect_cloud_accounts_test.go
Refactor to make things easier for the UI. The API now returns only the array of accounts instead of an object containing the array.
none
Updated test that validates the structure of the response.
Verify the response looks ok:
```
> curl localhost:9001/api/connect-cloud/accounts -H 'Connect-Cloud-Base-Url: https://api.staging.connect.posit.cloud' -H 'Authorization: Bearer xxx'
[{"name":"mslynch","id":"01971209-2261-6d18-b04c-b4d6877ee683","permissionToPublish":true}]
```
> simplify account list API response

- internal/clients/connect_cloud/account.go
- internal/services/api/get_connect_cloud_accounts.go
- internal/services/api/get_connect_cloud_accounts_test.go
Add a `displayName` field in the Connect Cloud account list response. We'll want to display this field in the UI. `name` may still be useful, so we're keeping it around for now.
Simple field mapping from the Cloud API call to the agent response.
none, until the UI starts using this field
Updated API test to add this field.
This curl should show the new field:
```
curl localhost:9001/api/connect-cloud/accounts -H 'Connect-Cloud-Base-Url: https://api.staging.connect.posit.cloud' -H 'Authorization: Bearer xxx'
```
> add display name to connect cloud accounts response

- CONTRIBUTING.md
- extensions/vscode/CONTRIBUTING.md
I spent a time-boxed 30 minutes to try to improve our CONTRIBUTING guide, mainly around VS Code extension development using the extension development host.
With new people working on the Publisher I thought I'd capture some additional notes in our CONTRIBUTING guides and clean up some things to hopefully make the next people who setup a development environment have an easier time.
I tagged some of the newer people working on the project in the hopes of getting your reviews.
Would this have been helpful when starting work on Publisher? 
Is there anything obvious I missed?
> chore: Improve extension dev CONTRIBUTING guide

- .gitignore
> add cmd/publisher/__debug_bin* to .gitignore

- test/e2e/code-server-entry.sh
- test/e2e/justfile
Resolves https://github.com/posit-dev/publisher/issues/2755.
Uses docker compose to execute the command after ensuring the service is running.
none
In `test/e2e`, rebuild your images using `just build-images`, then run `just`.
> install extension on every e2e run

- internal/services/api/get_connect_cloud_accounts.go
- internal/services/api/get_connect_cloud_accounts_test.go
At some point I broke this - we're sending `Authorization: Bearer Bearer xxx` instead of `Authorization: Bearer xxx`.
The extension sends the Authorization header with `Bearer`, and our API client constructor needs just the token value, so we parse the value given in the header.
Create a credential - you should no longer get an error after hitting Authorize on the device auth page.
> fix cloud client creation for account endpoint

- internal/config/types.go
- internal/publish/connect_cloud/content_request_base.go
- internal/publish/connect_cloud/content_request_base_test.go
Resolves https://github.com/posit-dev/publisher/issues/2679.
Resolves https://github.com/posit-dev/publisher/issues/2802.
Secrets/env vars, access control, and vanity name will all be respected.
Updated unit test to ensure the fields get mapped to the request.
Set the new properties on your content and ensure they're reflected in Connect Cloud.
> add support for Connect Cloud secrets, access control, and vanity names

- extensions/vscode/package.json
- extensions/vscode/src/api/types/contentRecords.ts
- extensions/vscode/src/extension.ts
- extensions/vscode/src/multiStepInputs/common.ts
- extensions/vscode/src/multiStepInputs/newConnectCloudCredential.ts
- extensions/vscode/src/test/unit-test-utils/factories.ts
- extensions/vscode/src/views/homeView.ts
- extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
- extensions/vscode/webviews/homeView/src/stores/home.ts
Resolves #2842
Resolves #2843
Resolves #2844
Resolves #2680
Resolves #2775
The intent of this PR is to fix a few known bugs for Connect Cloud support ahead of the bug bash.
A lot of the fixes are about making the messaging Connect Cloud friendly by conditionally displaying something different when the associated product is Connect Cloud or just simple rewording. There are other fixes that were a little more involved like using the account name vs the account display name when saving credential data so links would be correct. This also enabled the credential look-up for deployments to be correct because we could use the account name.
None because Connect Cloud support …
> Fixing multiple bugs for Connect Cloud support

- extensions/vscode/src/multiStepInputs/multiStepHelper.ts
Resolves #2777 
This PR updates the polling interval default to be every 2 seconds to match the updated device auth polling interval in this PR: [#1347](https://github.com/rstudio/lucid-auth/pull/1347)
The new polling interval will apply to all the polling done for Connect Cloud like the device auth token polling and the account polling.
More responsive multi-stepper experience when creating a new credential for Connect Cloud.
Existing E2E tests succeeded locally for this branch.
Verify creating a new credential for Connect Cloud is faster.
> Updating the polling interval default to 2 seconds

- extensions/vscode/CONTRIBUTING.md
There was a typo in the command for rebuilding the webview of the extension.
> docs: fix typo in webview extension command

- internal/clients/connect_cloud/client_connect_cloud_test.go
- internal/clients/types/types.go
- internal/publish/connect_cloud/content_request_base.go
- internal/publish/connect_cloud/content_request_base_test.go
- internal/publish/connect_cloud/create_deployment.go
- internal/publish/connect_cloud/publish_to_server.go
Turns out we were using the API wrong - we have to pass a different revision object depending on whether this is the create or update content request.
Resolves https://github.com/posit-dev/publisher/issues/2869.
Revision settings will properly apply on redeploy.
Added a test case for setting RevisionOverrides.
Redeploy and change a revision setting, like primary file or python version.
> set NextRevision or RevisionOverrides based on whether this is the first deploy or not

- internal/clients/types/types.go
- internal/publish/connect_cloud/await_completion.go
- internal/publish/connect_cloud/await_completion_test.go
Old:
New:
Resolves https://github.com/posit-dev/publisher/issues/2820.
Use the new error fields from Connect Cloud to present to the user.
Users will see more friendly error messages.
Updated unit test to reflect new errors.
Make a publish attempt that fails to Connect Cloud and verify the error looks ok.
> use connect cloud error messages from the API

- CONTRIBUTING.md
I removed the direct linking to 1p vault.  It has been added as a bookmark in the publisher slack channel instead.
> Update CONTRIBUTING.md info for test user authentication

- docs/configuration.md
Resolves https://github.com/posit-dev/publisher/issues/2949.
> configuration.md fixes for connect cloud

- internal/clients/types/types.go
Resolves https://github.com/posit-dev/publisher/issues/2978. We can't send an empty/null value for this field.
Unit testing isn't super valuable here. 
Deploy/redeploy to PCC using these settings:
```
[connect_cloud]
vanity_name = 'askdjldjkfjke'
```
> use omitempty on access for connect cloud

- extensions/vscode/src/views/homeView.ts
- extensions/vscode/webviews/homeView/src/App.vue
- extensions/vscode/webviews/homeView/src/stores/home.ts
- test/e2e/tests/integration-requests.cy.js
> connect cloud product guard

- internal/publish/connect_cloud/content_request_base.go
- internal/publish/connect_cloud/content_request_base_test.go
Resolves https://github.com/posit-dev/publisher/issues/2992.
Missed a certain test case that results in a nil dereference.
Added test cases to cover this path.
Follow reproduction steps in the ticket.
> fix nil pointer deref in access control code

- CHANGELOG.md
- docs/installation.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
Releasing pre-release version 1.19.1.
> version 1.19.1

- CHANGELOG.md
- docs/installation.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
> release 1.20.0

- extensions/vscode/src/api/types/configurations.ts
- extensions/vscode/src/types/messages/webviewToHostMessages.ts
- extensions/vscode/src/views/homeView.ts
- extensions/vscode/webviews/homeView/src/HostConduitService.ts
- extensions/vscode/webviews/homeView/src/components/views/Integrations.vue
- extensions/vscode/webviews/homeView/src/stores/home.ts
- internal/services/api/get_integrations.go
> squish branches 

- CHANGELOG.md
- docs/index.md
- extensions/vscode/README.md
> docs: integration requests

- .github/workflows/main.yaml
- .github/workflows/nightly.yaml
- Add the e2e tests to the nightly CI run
- Add the e2e tests on branch merges to main branch
Closes #2987 
I didn't gate/block/rollback anything on test failures, but could discuss adding if anyone thinks that would be beneficial
n/a
all e2e tests
> e2e tests: 2987 add e2e to nightly ci and on merge to main branch

- CHANGELOG.md
- docs/installation.md
- extensions/vscode/CHANGELOG.md
- install-publisher.bash
Releasing pre-release version 1.21.0
- Followed CONTRIBUTING
- Manually copied changes made to `extensions/vscode/CHANGELOG.md` to the main changelog
- Added a new `[Unreleased]` header to collect changes for the next release
> Prep for 1.21.0 pre-release

- .github/workflows/generate-licenses.yaml
Refactor license workflow validate-inputs job to a step. This will cleanup the job list so only one job will be reported like our other workflows.
Move the job to a step so the entire workflow is reported under a single job instead of two like it currently is.
Before
After
> refactor(ci): Move generate-licenses workflow job to a step

- .github/workflows/nightly-prerelease.yaml
Now that the nightly-prerelease workflow is successfully triggering releases we can re-enable the nightly prelease schedule
Related https://github.com/posit-dev/publisher/pull/3090
- Verified a manual dispatch of nightly-prerease works including triggering release.yaml and those releases appear in the marketplaces successfully
- Uncomment the schedule
From [the manual dispatch](https://github.com/posit-dev/publisher/actions/runs/17738940284):
Which [successfully triggered release.yaml](https://github.com/posit-dev/publisher/actions/runs/17738956530)
v1.23.1 is now available at all of your favorite marketplaces. …
> Renable nightly prelease schedule

- CONTRIBUTING.md
Update CONTRIBUTING to clarify waiting on main.yaml workflows before tagging a release
Related #3062
> Update CONTRIBUTING to clarify waiting on main.yaml workflows before tagging a release

- .github/dependabot.yml
- .github/workflows/pull-request.yaml
- CONTRIBUTING.md
Enable Databot to maintain all of our various dependencies.
Fixed https://github.com/posit-dev/publisher/issues/1174
- Leverage existing research in the linked issue
- Add all known areas of the project that has npm and Python dependencies
- Also add other things like GitHub Actions, Docker, and test data dependencies and opt for longer schedule periods for Docker and test data
- Disable upload.yaml for Dependabot PRs as that currently fails is is not critical, it will occur when the PR merges and the main.yaml workflow is executed
- Update CHANGELOG relatd to Dependabot
Before merging we need to give Dependabot a CONNECT_LICENSE secret.
> Enable Dependabot for all dependencies

- .github/workflows/e2e.yaml
- test/e2e/cypress.config.js
- test/e2e/support/commands.js
- test/e2e/support/oauth-task.js
- test/e2e/support/playwright-utils.js
- test/e2e/support/publish-success-task.js
- test/e2e/support/selectors.js
- test/e2e/support/sequences.js
- test/e2e/support/shared-browser.js
- test/e2e/tests/common.cy.js
- test/e2e/tests/credentials.cy.js
- test/e2e/tests/deployments.cy.js
- test/e2e/tests/embedded-deployments.cy.js
- test/e2e/tests/error-err-config.cy.js
- test/e2e/tests/integration-requests.cy.js
- test/e2e/tests/multi-stepper-negative.cy.js
- Started as error scenario tests for the multi-stepper.  
- Add and updated some support functions.  
- Refactor the existing tests to use the support functions and simplify them a bit.
- Consolidate and move the tasks from the cypress config to the oauth-task.js.
- Add a cleanup command for PCC deploys so we delete content on the cloud server after the test completes and cleanup db.
- Fix the debug flag so videos are recorded and extra logging enabled CI and locally when set `true`.
- I added quite a few comments/documentation around the tests and support functions as well.
Closes #3043
Add negative tests around multi-stepper, speed up execution, clean test data, and improve test documentation/comments.
- - [x] Documentation …
> Add additional negative tests and error scenarios, support functions, refactor/simplify existing tests, and better documentation
