posit-dev/publisher

.github/workflows/publish.yaml
Splits the publishing workflow into two separate jobs so it is easier to re-run them.
Resolves #1897
=> Split publishing workflow into two separate jobs

internal/services/api/delete_deployment.go, internal/services/api/delete_deployment_test.go, internal/services/api/deployment_dto.go, internal/services/api/get_configuration_test.go, internal/services/api/get_deployment.go, internal/services/api/get_deployment_test.go, internal/services/api/get_deployments.go, internal/services/api/get_deployments_test.go, internal/services/api/patch_deployment.go, internal/services/api/patch_deployment_test.go, internal/services/api/post_deployment.go, internal/services/api/post_deployment_test.go, internal/services/api/post_deployments.go, internal/services/api/post_deployments_test.go
This PR adds support for an optional `dir` query parameter to the deployment API endpoints:
* GET /api/deployments
* GET /api/deployments/$NAME
* POST /api/deployments
* POST /api/deployments/$NAME
* PATCH /api/deployments/$NAME
* DELETE /api/deployments/$NAME
The directory is relative to the workspace root directory, and cannot escape it (the API should return a 400 if you provide a path that would be outside of the workspace root).
It also populates the returned configuration DTO with a new `projectDir` field that contains the subdirectory (again, relative to the workspace root).
This is part of https://github.com/posit-dev/publisher/issues/1844 and part of https://github.com/posit-dev/publisher/issues/1851.
- - [ ] …
=> Add subdirectory support to deployments API

internal/services/api/get_config_python_packages.go, internal/services/api/get_config_python_packages_test.go, internal/services/api/get_config_r_packages.go
This PR adds the `dir` parameter to the configuration-specific Packages APIs.
Same as the other APIs (#1860, #1873).
Added unit tests to the Python packages suite. There isn't a suite for the R packages API yet.
Run the agent in a parent directory (one or more levels up from your deployable projects). Access the Pacakges API from subdirectories:
```
$publisher ui -vv --listen=localhost:9001 &
curl localhost:9001/api/configuration/$NAME/packages/python?dir=test/sample-content/quarto-proj-py | jq
curl localhost:9001/api/configuration/$NAME/packages/r?dir=test/sample-content/quarto-proj-py | jq
curl localhost:9001/api/configuration/$NAME/packages/python?dir=test/sample-cont …
```
=> Add dir parameter to config packages api

internal/services/api/get_config_files.go, internal/services/api/get_config_files_test.go
This PR adds the `dir` parameter to the configuration-specific Files API.
Same as the other APIs (#1860, #1873).
Added unit tests.
Run the agent in a parent directory (one or more levels up from your deployable projects). Access the Files API from subdirectories:
```
$publisher ui -vv --listen=localhost:9001 &
curl localhost:9001/api/configuration/$NAME/files?dir=test/sample-content/quarto-proj-py | jq
curl localhost:9001/api/configuration/$NAME/files?dir=test/sample-content/quarto-proj-none | jq
```
=> Add dir parameter to files API

extensions/vscode/src/multiStepInputs/newDeployment.ts
This moves the entry point selection and the title entry up to the beginning of the New Deployment `multiStepInput`.
Resolves #1784 
The diff is strange because of the similar code blocks. I updated the `steps` object to have the new step number calculations and then moved the `inputEntryPointSelection` and the `inputTitle` entry methods to occur ahead of the credential collection.
To validate, you should create deployments on the following, making sure a deployment can be created and that the step numbers update appropriately to your selections:
[ ] a project with a single entry point, using an existing credential 
[ ] a project with a single entry point, creating a …
=> Select entrypoint first in new deployment input

extensions/vscode/src/views/logs.ts
Resolves #1790 
This PR will cause Publishing Log sections to automatically expand themselves upon receiving a failure message.
I've also taken the opportunity to add a small bullet to the beginning of each log message, as well as suppressing newline characters received in the log messages, since we can't display those correctly.
Simple set of changes. When encounter failure and viewing publisher log, you'll now see something like this:
Final success or failure messages do not have icons as a prefix, as shown in the following screenshot.
NOTE: This behavior only occurs when the log is actively being updated. If you open the log after the publishing has occurred, the …
=> Publishing Log: expand section on error and add bullets to log message lines

extensions/vscode/src/constants.ts, extensions/vscode/src/views/configurations.ts, extensions/vscode/src/views/contentRecords.ts, extensions/vscode/src/views/credentials.ts, extensions/vscode/src/views/homeView.ts
Resolves #1864 
I searched for any string occurrence of "posit.publisher." and moved context related definitions into constants file.
Verify functionality impacted:
[ ] Storage location for last selected deployment and configuration file
[ ] Availability of these command pallette commands once the Home View has initialized:
- Select Deployment
- New Deployment
- Go to Debug Log
- Go to Publishing Log
- Browse Deployment Server
- Show Content Logs
[ ] Context menu items or right-clicks
- View Deployment in Connect for successful deployments (content records), but not for pre-deployment or deployment errors
- Delete option (right-click menu) for credentials
=> Move VSCode context strings into constants file.

internal/services/api/get_configurations.go, internal/services/api/get_configurations_test.go, internal/services/api/get_deployments.go, internal/services/api/get_deployments_test.go
This PR adds a new `entrypoint` query parameter to the GET /api/configurations and GET /api/deployments endpoints. Only configurations with a matching `entrypoint` (or deployments whose configuration has a matching `entrypoint`) will be returned.
Part of #1847 
Added unit tests specific to the new parameter.
Test with curl:
```
curl -s 'localhost:9001/api/configurations?dir=test/sample-content/rmd-static-1&entrypoint=static.Rmd'|jq
curl -s 'localhost:9001/api/configurations?dir=test/sample-content/rmd-static-1&entrypoint=index.htm'|jq
```
=> Entrypoint filtering for configuration and deployment APIs

.github/workflows/lint.yaml, internal/credentials/keyring.go, internal/publish/r_package_descriptions.go
This adds our `just lint` command to the lint workflow which runs `ccheck`.
This ensures that our code has the license header as a part of CI.
Resolves #1906 
=> Fail CI if ccheck fails

docs/justfile, scripts/licenses.py
This PR changes the `just docs/licenses` target to run `python3` rather than relying on `/usr/bin/env python`
Resolves #1913
=> Use python3 to run licenses script

internal/services/api/post_packages_python_scan.go, internal/services/api/post_packages_python_scan_test.go, internal/services/api/post_packages_r_scan.go, internal/services/api/post_packages_r_scan_test.go
This PR adds the `dir` parameter to the package scanning APIs: POST /api/packages/r/scan and POST /api/packages/python/scan.
Part of #1851
Added unit tests for the new parameter.
```
curl -s localhost:9001/api/packages/python/scan?dir=test/sample-content/rmd-static-1 -XPOST
curl -s localhost:9001/api/packages/r/scan?dir=test/sample-content/rmd-static-1 -XPOST
```
etc.
requirements.txt/renv.lock should be created in the specified subdirectory, and only contain package dependencies discoverable from the code in that subdirectory.
=> Add subdirectory support to package scanning APIs

internal/initialize/initialize.go, internal/initialize/initialize_test.go, internal/inspect/detectors/all.go, internal/inspect/detectors/all_test.go, internal/inspect/detectors/html.go, internal/inspect/detectors/html_test.go, internal/inspect/detectors/infer.go, internal/inspect/detectors/notebook.go, internal/inspect/detectors/notebook_test.go, internal/inspect/detectors/plumber.go, internal/inspect/detectors/plumber_test.go, internal/inspect/detectors/pyshiny.go, internal/inspect/detectors/pyshiny_test.go, internal/inspect/detectors/python.go, internal/inspect/detectors/python_test.go, internal/inspect/detectors/quarto.go, internal/inspect/detectors/quarto_test.go, internal/inspect/detectors/rmarkdown.go, internal/inspect/detectors/rmarkdown_test.go, internal/inspect/detectors/rshiny.go, internal/inspect/detectors/rshiny_test.go, internal/services/api/post_inspect.go
This PR adds the `entrypoint` parameter to the POST /api/inspect endpoint.
Part of #1847
Rather than inspecting as usual and then filtering, the entrypoint is passed down to `InferType` so the inspectors can avoid a lot of I/O when an entrypoint is specified.
Added tests for when an entrypoint is specified.
```
curl -s -XPOST -d '{}' 'localhost:9001/api/inspect?dir=test/sample-content/rmd-static-1&entrypoint=index.htm' | jq
curl -s -XPOST -d '{}' 'localhost:9001/api/inspect?dir=test/sample-content/rmd-static-1&entrypoint=static.Rmd' | jq
curl -s -XPOST -d '{}' …
```
=> Add entrypoint filtering to the inspect API

internal/bundles/matcher/walker.go, internal/services/api/get_configurations.go, internal/services/api/get_configurations_test.go
This PR implements a recursive option to the GET /api/configurations endpoint.
Part of #1850 
Walk the tree looking for .posit directories; when one is found, list configurations from the parent directory. The built-in exclusions are applied to avoid excess directory traversals.
Added tests for the recursive flag.
```
curl -s localhost:9001/api/configurations?recursive=true | jq
$ curl -s 'localhost:9001/api/configurations?recursive=true&dir=test' | jq
$ curl -s 'localhost:9001/api/configurations?recursive=true&dir=test&entrypoint=simple.py' | jq
```
=> Recursive configuration API

extensions/vscode/src/api/resources/Configurations.ts
Follow up to #1925 which adds `recursive` param support to the `api.configurations.getAll()` method.
=> Add recursive param support to config getAll

internal/inspect/r.go, internal/inspect/r_test.go
This PR avoids invoking R to request `renv::paths$lockfile()` if there's an `renv.lock` in the project directory.
Follow-on to #1929 
Added a test for this behavior.
Inspect an R project that contains renv.lock, and one that doesn't.
If there's an renv.lock file, you shouldn't see a log line like:
```
level=DEBUG msg="Running command" cmd=/usr/local/bin/R args="-s -e renv::paths$lockfile()"
```
=> Only request renv::paths() if no renv.lock present

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/api/resources/Configurations.ts, extensions/vscode/src/constants.ts, extensions/vscode/src/entrypointTracker.ts, extensions/vscode/src/extension.ts, extensions/vscode/src/utils/files.ts, extensions/vscode/src/utils/inspect.ts
This PR adds a new context to the extension that tracks if the active document is an entrypoint with a `ContentType` that is known (aka not `Unknown`)
If the active document is an entrypoint - found via `/api/inspect` - we show a button which currently is non-functional, but will lead a user through deploying.
Note that `licenses.md` didn't need to change since `vscode-uri` is already included from dependencies.
Start of #1848
The approach here was to create a tracker that created all of the listeners needed itself, tracked the documents it needed to, and updated the context.
This way the extension could create a `DocumentTracker` and add it to its `diposables` with no …
=> Add document tracker to set `activeFileEntrypoint` context

extensions/vscode/src/api/resources/Configurations.ts
Follow up to #1929 that adds support for the param to the API module.
=> Add inspect recursive param support to API module

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
VSCode `1.91.0` added a new setting `accessibility.underlineLinks` which does what it says on the tin
> To make links easier to distinguish from regular text in the workbench, you can enable the setting accessibility.underlineLinks to underline links.
https://code.visualstudio.com/updates/v1_91#_link-underlines
This PR ensures all of our text links (`<a>`) support the feature and toggle appropriately.
<details>
https://github.com/posit-dev/publisher/assets/19917631/eb4d859f-7771-4c7f-a4ff-1cd501048800
</details> 
Resolves #1934 
The injected CSS does the below
```
.monaco-workbench p>a {
text-decoration: var(--text-link-decoration);
}
```
The …
=> Support link underlines accessibility setting

internal/services/api/get_configurations.go, internal/services/api/get_deployments.go
This fixes the case where there are no Deployments or Configurations and the `recursive` param was passed. In that case the `response` array was never created and was being encoded to `null`.
This fixes that by instantiating the `response` immediately as a variable length slice.
If `recursive` isn't passed it will be overwritten by `readLatestDeploymentFiles`
If `recursive` is passed and nothing is found it will still be an empty `[]`
Fixes #1937 
Test with deployments/configs, without, and recursively
=> Fix empty array response for recursive resources

.prettierignore, extensions/vscode/package.json, extensions/vscode/src/api/resources/Configurations.ts, extensions/vscode/src/api/resources/ContentRecords.ts, extensions/vscode/src/api/resources/Files.ts, extensions/vscode/src/api/resources/Packages.ts, extensions/vscode/src/bus.ts, extensions/vscode/src/constants.ts, extensions/vscode/src/entrypointTracker.ts, extensions/vscode/src/multiStepInputs/newConfig.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/multiStepInputs/selectConfig.ts, extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/types/shared.ts, extensions/vscode/src/utils/names.ts, extensions/vscode/src/utils/webviewConduit.ts, extensions/vscode/src/views/configurations.ts, extensions/vscode/src/views/contentRecords.ts, extensions/vscode/src/views/credentials.ts, extensions/vscode/src/views/helpAndFeedback.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/src/views/logs.ts, extensions/vscode/src/views/project.ts, extensions/vscode/src/watchers.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/DeployButton.vue, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
Resolves #1960 
Added a new message which is returned after the extension believes the initialization queries have been completed.
Then I added a variable within the home store that indicates if initialization is complete or not.
Message handlers update the value of the variable within the home store, and then the EvenEasierDeploy vue reacts to the value of that ref.
End Result:
https://github.com/user-attachments/assets/550e19da-5b53-4f6f-9fda-f5f6a922908b
Open a very large folder with VSCode, activate the publisher and verify the proper views are visible after initialization.
Do the same with a small folder.
=> Disable homeview's Easy Deploy View until ready

extensions/vscode/src/constants.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/types/shared.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/DeployButton.vue, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
Resolves #1852 
The changes needed to implement this proved to be pretty much as expected.
1. Needed to take into account projectDir when selecting or matching configurations and deployments
2. Needed to update API calls to be recursive
3. Needed to update new deployment process to be able to create unique names per the project directory
4. File watchers needed to watch recursively
5. Needed to pass in projectDir when calling deploy api
Unfortunately, there were a number of changes required to maintain functionality once changes were started. It would be best to walk through the individual commits, to understand what is being done.
[recursive inspection, create …
=> Basic support for multi-folder deployment creation, selection and deployment

.prettierignore, extensions/vscode/package.json, extensions/vscode/src/constants.ts, extensions/vscode/src/multiStepInputs/selectConfig.ts, extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/types/shared.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
- Use selected Deployment's `projectDir` for "Select Active Configuration"
- [Support duplicate names within subdirectories
Resolves #1944 
Resolves #1853 
=> Use of project dir and new deployment selector for subdirectory support w/ select configuration support

extensions/vscode/src/api/resources/Configurations.ts, extensions/vscode/src/api/resources/ContentRecords.ts, extensions/vscode/src/api/resources/Files.ts, extensions/vscode/src/api/resources/Packages.ts, extensions/vscode/src/bus.ts, extensions/vscode/src/entrypointTracker.ts, extensions/vscode/src/multiStepInputs/newConfig.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/multiStepInputs/selectConfig.ts, extensions/vscode/src/utils/names.ts, extensions/vscode/src/views/configurations.ts, extensions/vscode/src/views/contentRecords.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/src/watchers.ts
refactored changes to make dir mandatory for API calls. Updated watchers for package files to work with subdirectories, and updated package views to work in subdirectories. Updated Bus callbacks to be typesafe.
Refactored changes to make dir mandatory for API calls. 
Updated watchers for package files to work with subdirectories
Updated package views to work in subdirectories. 
Updated Bus callbacks to be typesafe.
Resolves #1855 
Reolves #1949 
Use VSCode to open project's subdirectory directly as well as from a few parent subdirectories up.
With these projects, verify the functionality related to packages for both R and Python projects.
Be sure to both manually and …
=> Force directory param to be required on API calls and refactor config-based watchers to work in subdirectories

extensions/vscode/src/views/homeView.ts
Closes #1854 (Use selected Deployment's `projectDir` to list files and include/exclude)
After everything was updated to pass in the projectDir from the activeContentRecord, adding and removing files from the config.Files section would not work correctly when the project was not located at the top root dir that VSCode had opened.
This was because the files API returned an ID that included the projectDir, and this was an incorrect value for the config file. I've created issue #1950, but this PR implements a simple workaround that removes the projectDir from the path represented in the id of a file.
Make sure you can add and remove exclusions from the files view, with the …
=> Enable files view to work when project is located in subdirectory

extensions/vscode/src/multiStepInputs/newConfig.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/multiStepInputs/selectConfig.ts
Show the projectDirs in the multit-step selectors for entrypoints
Part of #1845 
The three multi-steppers were updated in the same way, adding the projectDir to their detail attribute.
You can invoke them by:
- New Config from config view
- New Deployment when there are multiple entrypoints
- Select Config, when there are multiple entrypoints with the same content type as the current deployment.
You should verify that the projectDir is shown in those multiSteps.
=> Show project dir when selecting entrypoints

extensions/vscode/src/views/configurations.ts
Resolves #1951 
- move progress indicator to configurations view
- update clone initial name for projectDir
- add progress indicator for children tree population (relies upon sometimes slow API)
- Verify operations work for configurations view
- Verify that when creating a new configuration when VSCode has opened a folder containing a lot of entrypoints, that the progress indicator is shown within the Configurations view (vs. down below in the bottom status line).
- Verify that when opening very large directory tree and switching over to publisher, that configurations window when expanded shows progress indicator until it is able to load.
=> Updates to configurations view to work with subdirectories

extensions/vscode/src/views/contentRecords.ts
Resolves #1952 
Only change required to make deployments view work in multi-subdirectory world was to add a progress indicator when calling the API.
Simply updated per existing patterns
Verify loading and refresh of deployment view (expanded) when VSCode has opened a large folder and a small one.
=> Add progress indicator for loading of deployments view

extensions/vscode/src/views/homeView.ts
Resolves #1958 
Adds a HomeView progress indicator while API calls are outstanding
Wrapped API calls with VSCode's `withProgress` call, showing on the HomeView.
Verify you see a progress indicator within HomeView when it is initializing, after switching to publisher view. This will be very visible if you open a very large folder in VSCode as the base dir.
=> Add progress indicator for homeview APIs

extensions/vscode/src/views/homeView.ts, internal/services/api/files/services.go, internal/services/api/files/services_test.go
This PR changes the Files API's `id` field to be a path relative to the requested directory instead of the workspace root. It also removes the workaround introduced in #1954.
Fixes #1950 
Added a test for the case where the requested directory is a subdirectory of the root.
Run the VSCode extension, with a project and configuration file in a subdirectory of the root. Use the UI to exclude and include files; it should still work and the configuration file should show the paths correctly (relative to the project dir, not the workspace root).
=> Relative file IDs

extensions/vscode/src/multiStepInputs/newConfig.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/multiStepInputs/selectConfig.ts
Uses [`path.sep`](https://nodejs.org/api/path.html#pathsep) to display separation characters (`\` or `/`) based on the  platform.
Resolves #1980
=> Use path.sep for path strings

extensions/vscode/src/views/homeView.ts, extensions/vscode/src/watchers.ts
PR feedback changes. This simplifies the config watcher to use `cfg.configurationPath`
=> Simplify ConfigWatcherManager construction

extensions/vscode/src/views/homeView.ts
This PR improves the strings for the Deployment quick picker by:
- Only showing the path if it isn't `.`
- Always showing the path even if there is a credential error
- Using the `•` separator so it is a bit easier to read
<details>
</details> 
Part of #1854
=> Improve deployment quick pick detail string

extensions/vscode/src/views/homeView.ts, extensions/vscode/src/watchers.ts
This PR reverts some of the refactoring done in the nested project work and utilizes `activeConfiguration.projectDir` directly rather than using only `activeContentRecord.projectDir` since all of these operations rely on the configuration. This makes it a bit easier to understand what some of those functions are relying on, and a bit simpler.
This also makes the `activeConfigChanged` listener function use optionality again rather than terminating early to avoid errors caused by the active content record becoming `undefined` but the file watchers were still firing.
Part of [#1984](https://github.com/posit-dev/publisher/issues/1984)
=> Use `activeConfiguration.projectDir` where appropriate

extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/stores/home.ts
To fix the regression where we lost updates to the selected configuration when configuration(s) data updated without undoing the refactoring work we can make `selectedConfiguration` entirely `computed` similar to `serverCredential`.
This PR removes any specification of `selectedConfiguration.value` and makes it computed using the `configurations` in the store and `selectedContentRecord.configurationName`. It falls back to `undefined` just like `selectedConfiguration` did.
This keeps `selectedConfiguration` updated without the need to ever set it.
The name `selectedConfiguration` stayed to make this PR a bit quicker and easier to review.
Resolves #1984
Try:
- updating …
=> Make webview home store `selectedConfiguration` computed

extensions/vscode/src/api/axios.d.ts, extensions/vscode/src/api/client.ts, extensions/vscode/webviews/homeView/src/axios.d.ts
PR feedback follow-up. Adds the `ts` attribute as an optional attribute for the `AxiosRequestConfig` so we get type safety.
=> Add timestamp to AxiosRequestConfig type

extensions/vscode/src/utils/url.ts, internal/clients/connect/client_connect.go, internal/clients/connect/client_connect_test.go, internal/clients/http_client/http_client.go
An authenticating proxy such as the one in front of [palm](https://pub.palm.ptd.posit.it/) may return a login page redirect for an unauthenticated API request. We make such a request when testing a server URL without an API key (during the Add Credential flow in the extension). This PR changes loosens the URL-only validation to consider HTML responses to be successful. The next validation step includes an API key, and remains strict.
Fixes #1974
Added a unit test for this case.
Try various server URLs:
* https://rsc.radixu.com
* https://pub.palm.ptd.posit.it/
* ~https://pub.palm.ptd.posit.it/connect/~
* https://google.com
=> Handle JSON errors in server validation

extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/stores/home.ts
This PR solves a race condition and other issues found around creating new deployments.
The previous edge-case capturing logic was re-introduced that handled optionally sending the selection to the webview. It needs to be optional to avoid this race condition where the new deployment async code fires before the file watcher listeners. It also now handles `undefined` and `null` again so we can specify if we want to force de-selection or just update data.
Some equality checking was also fixed which was causing some of the errors seen.
Resolves #1989
- Ensure last selection loads correctly on Extension init
- Ensure that a deleted deployment causes the selection to be …
=> Avoid race condition when creating new deployments

internal/inspect/python.go, internal/inspect/python_test.go, internal/inspect/r.go, internal/inspect/r_test.go
This PR avoids repeatedly invoking R and Python interpreters to query their versions, by caching those versions.
Draft PR because I need to think about whether we need to not cache the `.pyenv/shims/python` interpreter, which runs different interpreters based on pyenv settings and potentially `.python-version` files. 
Follow-on to #1929 
- - [x] Performance
Cache interpreter versions in agent memory, using interpreter path as the key.
Existing tests have been updated.
Inspect projects (especially recursively). We should only request each R or Python interpreter version once.
=> Cache interpreter versions

extensions/vscode/src/watchers.ts
This PR uses Configuration's `projectDir` to setup the two package file system watchers for the Python package file, and the R package file.
With the simplification of the `ConfigWatcherManager` in #1977 I removed the need for `contentRecord`, but didn't replace the `projectDir` used to reference the Configuration. This fixes that.
Test that the Python and R Packages views are reactive in a nested and non-nested project.
=> Use projectDir for package file watchers

internal/inspect/python.go, internal/inspect/python_test.go
This PR makes the requirements.txt reader properly ignore indented comments, such as those produced by `uv`.
Fixes #2010
Added a test for `ReadRequirementsFile`.
Add comments to your requirements.txt file that begin with a space:
```
numpy
pandas
statsmodels
```
The comments should not show up in the Python Packages view.
=> Handle indented comments in requirements.txt

extensions/vscode/src/types/quickPicks.ts, extensions/vscode/src/utils/titles.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/components/DeployButton.vue, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
This PR addresses an issue where `ConfigurationError` selected configurations were not handled well:
- the edit button to edit the configuration would not appear
- the selection would not propagate to the webview
- the "Edit the Configuration" error link would not open the configuration for editting
This bug came from a combination of the refactor in #1961 removing updates to the selected configuration when configurations were sent to the frontend, and from the move to make selected configurations computed in the webview.
The approach here was to always grab the selected Configuration even if it was in error and handle the typing in the areas that did not support `ConfigurationError` yet.
- Test Configuration Errors (invalid schema) in a nested and non-nested workspace root
- Ensure the …
=> Handle configuration errors in selected configuration

extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/types/quickPicks.ts, extensions/vscode/src/types/shared.ts, extensions/vscode/src/views/homeView.ts
Resolve #2003 
Initiating deployment after selection of existing or new deployment occurs.
I avoided race conditions with new deployments and configs by collecting the necessary API parameters for publishing directly from the multi-steppers that called the backend APIs after collecting the input from the user. Since they have confirmation from the APIs that the associated file updates were successful, then by using these same values, they are guaranteed to exist. This avoids trying to find the matching objects within the local caches, which are being asynchronously updated by the file watchers.
Verify functionality within both mutli-folders and single folder projects …
=> Publish from entrypoint file click

extensions/vscode/src/views/homeView.ts
resolves #2022 
This PR started out with implementing some simple updates requested within PR #2005. However, one of the comments questioned the failures during a few of the flows when there were no credentials available to the deployment record. A solution is provided for that problem as well, which makes a change to the workflows.
Those impacted scenarios are:
- Prompt for credentials when publishing entrypoint - when single deployment or compatible selected deployment has no credential.
- ~~Prompt for credentials during selectNewOrExistingConfig, when missing.~~
Each of the changes has been committed separately. This should help facilitate the easiest review. There …
=> Invoke creation of credentials rather than immediate failure, plus followup items for pr2005

internal/services/api/api_service.go, internal/services/api/get_entrypoints.go, internal/services/api/get_entrypoints_test.go, internal/util/slice.go
This PR adds the GET /api/entrypoints endpoint, which scans the project directory for potential entrypoints by file suffix. It excludes the standard exclusions, as well as some files with the right suffix that aren't good entrypoints. The returned files might be entrypoints; they need to be inspected with /api/inspect to be sure.
Fixes #2029
Added a basic unit test for the new endpoint.
```
just build
curl -s localhost:9001/api/entrypoints -XPOST |jq
```
=> Fast entrypoint scanning

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/style.css
This PR removes anchors with empty `href` attributes from the webview to avoid opening new tabs in Workbench.
The removal of `href` changed the default styling so a new class was introduced to avoid any changes.
Resolves #2034
=> Avoid opening new tabs with anchors in workbench

internal/inspect/python.go, internal/inspect/python_test.go
Fixes #2033
Update the comment-ignoring regexp to handle lines that are all whitespace.
Updated existing unit test to catch this.
Have a whitespace-only line in requirements.txt. It shouldn't show up in the Python Packages view.
=> handle whitespace-only lines in requirements.txt

internal/clients/connect/client_connect_test.go, internal/inspect/dependencies/pydeps/project_dependencies.go, internal/inspect/dependencies/pydeps/project_imports.go, internal/inspect/dependencies/pydeps/qmd_contents.go, internal/inspect/detectors/all.go, internal/services/api/post_inspect.go
Fixes #2032
There are a number of places in the Go code where we return nil when a result set would be empty. This PR changes those to return an empty slice. We only return nil on error returns, where the slice value won't be used by the caller.
Existing tests should pass.
Open an empty folder, and try to add a deployment.
=> Return empty array instead of nil

extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/App.vue, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/OverlayableView.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
Resolves #1995 
Resolves #2016 
This PR addresses user feedback which indicated confusion within the UX when the multi-stepper inputs / selections were in progress.
I've implemented a new component that can activate an overlay with an opacity set to indicate the WebView view is disabled. This is then invoked from within the extension's homeView when sequences are started which will possibly update the selection.  For example, this is what the view looks like when the user initiates creating a new deployment:
Dark mode:
Enabled without a multi-stepper invoked:
with Overlay enabled and multi-stepper initiated:
Light mode:
Enabled without a multi-stepper invoked:
with …
=> Deactivate Easy Deploy View when selections in progress

.github/workflows/home-view-unit-test.yaml, .github/workflows/pull-request.yaml, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json, extensions/vscode/webviews/homeView/src/HostConduitService.test.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/stores/home.test.ts, extensions/vscode/webviews/homeView/src/utils/date.test.ts, extensions/vscode/webviews/homeView/src/vscode.ts, extensions/vscode/webviews/homeView/vite.config.ts
This PR adds the beginnings of test infrastructure, in Vitest, for our Vue Home webview view
The approach here was to identify some utilities that didn't require much work at all to begin testing, and grab a core piece of code - in this case the `HostConduitService` and get some more complicated tests in place.
This sets up how we can use the Home store, the HostConduitService, and sending some messages (using Mocks where needed)
=> Add start of Vitest infrastructure for Home webview

extensions/vscode/src/state.ts, extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/types/shared.ts, extensions/vscode/src/views/homeView.ts
This PR moves out some of the state logic in `homeView.ts` to a new `PublisherState` class to make it a bit easier to reason about our lists of resources (Content Records, Configurations, and Credentials) and the current selections.
I kept the logic exactly the same, just moved the location of the code. I did it one resource at a time so the commits may be helpful to review this in segments.
=> Split out state logic to `PublisherState` class

internal/inspect/detectors/quarto.go, internal/inspect/detectors/quarto_test.go, internal/inspect/detectors/testdata/dashboard/inspect_dashboard.json
This PR adds support for detecting Quarto documents whose output format is `revealjs`, in addition to the current `html` support.
Fixes #2065
Updated the Quarto inspector to also look at the `revealjs` metadata in the output from `quarto inspect`. 
Added a unit test for this case.
Inspect the project in https://github.com/posit-dev/posit-conf-survey/; the configuration type should be `quarto-shiny`.
=> Handle Quarto revealjs output format

internal/bundles/matcher/walker.go, internal/bundles/matcher/walker_test.go
When walking the file tree using an inclusion/exclusion list, we need to visit subdirectories unless they are excluded. Even if there's not an explicit inclusion, a file pattern might match within the subdirectory.
Fixes #2075
Don't prune the search of the filesystem on a directory node when there's no match; only prune it if there's an explicit exclusion.
Added a test for this case.
Configure your project to include specific files (no `*` pattern), including some files in a subdirectory. When you deploy, those files should be included even though you didn't add a pattern for their parent directory.
=> Find matches in subdirectories

extensions/vscode/src/constants.ts, extensions/vscode/src/views/credentials.ts, internal/credentials/credentials.go, internal/credentials/credentials_test.go, internal/credentials/errors.go
Resolves #2062 
Partially addresses #1831 
This PR introduces automatic credentials, which are imported from environment variables.
Since we do not want environment variables to persist, the actual keychain storage does not include these new types of credentials. Instead, they are inserted into the memory copy of the store and are removed before that store is persisted.
The environment credential has a fixed GUID of "00000000-0000-0000-0000-000000000000". This allows us to identify it, provide more contextual error messages, and restrict operations (deletes are not allowed).
Validation of the URL is not done at creation time. This will show up as a normal connectivity …
=> Allow credentials to be specified via environment variables

extensions/vscode/src/api/types/events.ts, extensions/vscode/src/events.ts, extensions/vscode/src/views/deployProgress.ts, extensions/vscode/src/views/logs.ts
Resolves #2057 
As discussed with the team, we'll be implementing this within the UX only, while the agent continues to process the deployment in the background.
A new cancel button is available on the deployment in progress message. Clicking this causes a mock `publish/failure` message to be sent out and then causes all newer messages received within the same localId, to be discarded.
Components will continue to provide status per the file watchers, so a special canceled notification provides some direction as to what to expect.
Validate full deployments complete.
Validate you can cancel one, seeing the error notification message as indicated above. Open the log and …
=> Provide ability to dismiss deployment in progress

internal/inspect/detectors/quarto.go
Fixes #2059 
Quarto inspection needs to proceed for jupyter notebook when an entrypoint file is specified.
```
$(just executable-path) ui -vv --listen=localhost:9001
curl -s -XPOST -d '{}' 'localhost:9001/api/inspect?dir=internal/inspect/detectors/testdata/stock-report-jupyter' | jq
curl -s -XPOST -d '{}' 'localhost:9001/api/inspect?dir=internal/inspect/detectors/testdata/stock-report-jupyter&entrypoint=stock-report-jupyter.ipynb' | jq
```
Both should return two configurations:
```
[
{
"configuration": {
"comments": [
" Configuration file generated by Posit Publisher.",
" Please review and modify as needed. See the documentation for more options:",
" …
```
=> Add jupyter notebook as valid type for quarto

extensions/vscode/src/api/types/contentRecords.ts, extensions/vscode/src/views/homeView.ts, internal/deployment/deployment.go, internal/deployment/deployment_test.go, internal/publish/publish.go, internal/publish/publish_test.go, internal/schema/schemas/record.toml
Small cleanup that moves computation of the logs URL for a piece of content to the backend and stores it in the deployment record, rather than computing it in the front end. This also ensures that trailing slashes are correct for the dashboard and direct URLs (matching how they are returned from Connect).
Fixes #1750
Updated existing tests.
"View Content Log on Connect" from the ellipsis menu in the home view should still work.
=> Logs url from backend

extensions/vscode/src/entrypointTracker.ts, extensions/vscode/src/utils/files.ts, extensions/vscode/tsconfig.json
VSCode treats editors and notebooks a bit differently and the `entrypointTracker` only tracked editors. With this PR it now tracks notebooks as well which adds the entrypoint button when an opened notebook is an entrypoint.
Resolves #2090
I upgraded our TypeScript configuration to target and use `ES2022` to support [`Object.hasOwn()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn)
The rest of the approach was to:
- Add listeners for notebooks mirroring the text editor listening
- Refactor functions to accept either a text document/editor or notebook document/editor since the behavior was essentially the same
Test the …
=> Show the entrypoint button in valid notebooks

extensions/vscode/src/state.ts, extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/types/shared.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts
I've refactored the types of DocumentSelector and SelectionState, ahead of a separate PR for #2049.
This change allows us to version the selection state structure being saved into the VSCode workspace storage and have enough information to make an API call to retrieve the last deployment file used, simply off of the information persisted.
Because of the version check, the previous saved selection will be thrown away. Once you have selected a deployment, the new structure is saved and used. You can confirm this by using the command palette to reload the window and confirm that your last deployment selection is restored.
=> Refactor DeploymentSelector and SelectionState

extensions/vscode/src/api/types/configurations.ts, extensions/vscode/src/bus.ts, extensions/vscode/src/multiStepInputs/selectNewOrExistingConfig.ts, extensions/vscode/src/state.ts, extensions/vscode/src/utils/filters.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/stores/home.ts
Part of addressing #1970 
If the extension is able to retrieve the previous selection from VSCode workspace storage, and the content record is valid and configuration can be found (valid or not), then skip the recursive API query for all deployments and configurations as we don't need the list yet.
This PR does also change the select deployment list to perform a full query first, matching the behavior of the multi-step flows. I was finding circumstances where the population of the content records within the homeView was not correct, so this change, while it does slow down the selection, does allow it to be correct.
We are balancing on the edge of needing to implement …
=> Skip recursive query of deployments and configurations if selection was saved and is present

extensions/vscode/src/types/quickPicks.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
Resolves #2102 
Updated EvenEasierDeploy UX so as to not require a full recursive query for deployments and configurations before showing the UX, when the workspace opened within VSCode does not have a previous selection recorded.
To do this, I've renamed the button to a more generic `Select Deployment...` and then updated the Select Deployment code to also include a list entry which allows creating a new deployment. I've also added two separators within the list, one for existing deployments and a second for new.
The following videos were recorded with an abnormally large project dir (my entire dev directory), but it nicely shows one of the worse cases we might see. …
=> Remove need for recursive deployment query from initial evenEasierDeploy

extensions/vscode/src/api/types/files.ts, internal/services/api/files/files.go, internal/services/api/files/services.go, internal/services/api/files/services_test.go, internal/services/api/get_config_files.go
The Files API populates the `size` field for directories with a total size of all contained files. There is a new `fileCount` field containing the count of files (not directories).
Added a test for this.
Run the agent, and access `/api/configurations/$NAME/files`.
=> Add file size and count for directories

internal/inspect/detectors/all.go
This PR sorts returned configurations by entrypoint and then by type; currently they are only sorted by entrypoint.
* For an Rmd, it will sort the `quarto` configuration before the `rmd` one (or `quarto-shiny` before `rmd-shiny`).
* For a notebook, it will sort the `notebook` configuration before the `quarto` one.
Fixes #2050
The sort order isn't tested; this PR doesn't add a test for it.
Inspect files the can have multiple deployment types, and see that the sort order of the offered configurations is correct.
=> Sort configurations of the same entrypoint by type

internal/services/api/files/files.go, internal/services/api/files/services.go, internal/services/api/get_configurations.go, internal/services/api/get_deployments.go, internal/services/api/get_entrypoints.go, internal/services/api/post_inspect.go, internal/util/symlink_walker.go
This PR introduces error handling in the file walkers for files not being found. This can happen if files are being removed while the walker is iterating.
Part of #2107
Unit tests don't exercise this case currently.
I ran this:
```
$(just executable-path) ui -v --listen=localhost:9001 &
while true; do curl -s -w '%{stderr}%{http_code}\n'  localhost:9001/api/configurations/default/files >/dev/null; done
```
in another shell:
```
uv venv .venv
us pip install notebook
cp -r .venv .venv2
rm -rf .venv2
```
Curl would always return a 500 at some point during the deletion; this should no longer happen.
=> Handle files being deleted

extensions/vscode/.eslintrc.json, extensions/vscode/src/commands.ts, extensions/vscode/src/dialogs.ts, extensions/vscode/src/multiStepInputs/multiStepHelper.ts, extensions/vscode/src/ports.ts, extensions/vscode/src/servers.ts, extensions/vscode/src/test/suite/extension.test.ts, extensions/vscode/src/utils/names.ts, extensions/vscode/src/utils/progress.ts, extensions/vscode/src/views/homeView.ts
Resolves: #2124 
ESLint rule was added and code was cleaned up. In each case where the await was removed, I looked at all existing callers and made sure they were using `await` or not, properly.
The errors reported by ESLint, once I added the rule and ran `npm run lint` were:
```
~/dev/publishing-client/extensions/vscode main > npm run lint
> publisher@99.0.0 lint
> eslint src --ext ts --max-warnings 0
/Users/billsager/dev/publishing-client/extensions/vscode/src/commands.ts
21:20  error  Async arrow function has no 'await' expression  require-await
/Users/billsager/dev/publishing-client/extensions/vscode/src/dialogs.ts
43:8  error  Async function 'confirmOK' has no …
```
=> Remove (and enforce) use of await expression when not needed

test/bats/contract/deploy.bats
Since we now only deploy the entrypoint file by default, the deploy tests had to be adjusted to allow for additional files to be added to deployments.
fixes: https://github.com/posit-dev/publisher/issues/2142
=> add additional files to deploy tests

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/constants.ts, extensions/vscode/src/utils/throttle.ts, extensions/vscode/src/utils/webviewConduit.ts, extensions/vscode/src/views/homeView.ts
Resolves #1970 
Resolves #2107 
The existing codebase had a basic throttling implementation for a few API calls. This PR built upon that as well as adding a throttling capability for our recursive calls in which we only wanted one outstanding call at a time, but we also didn't want to lose the latest initiated call.
For the most part, the APIs being initiated in the background by the file watchers were debounced, while the APIs being initiated off of user action were not.
Different debounce intervals were evaluated, with an eye for minimizing user visual impact while making a significant reduction in calls. I evaluated in the range of 100ms - 1 second and ended up …
=> UX: Add debounce and throttling to main query methods

extensions/vscode/package-lock.json, extensions/vscode/package.json, test/bats/contract/deploy.bats
Since migrating to fantasticon the `just package` step started failing in Windows with: ` No SVGs found in ./assets/icons`. https://github.com/posit-dev/publisher/actions/runs/10484447740/job/29038965557
There are a number of issues over the past year in the fantasticon repo about this.  The bootstrap team made a fork of the repo and fixed the issue.  This PR uses the fork and now passes:
https://github.com/posit-dev/publisher/actions/runs/10479307236/job/29024846908
fixes: https://github.com/posit-dev/publisher/issues/2144
=> use fantasticon fork

internal/deployment/deployment.go, internal/publish/publish.go, internal/publish/publish_test.go, internal/schema/schemas/draft/posit-publishing-record-schema-v3.json, internal/schema/schemas/draft/record.toml, internal/schema/schemas/posit-publishing-record-schema-v3.json, internal/schema/schemas/record.toml
#2099 added a new `logs_url` field to the content record TOML. This PR ensures that it is set on deployment (a case missed in the original PR), and updates the jsonschema for the content records so the new deployment records can be validated.
A schema update on the CDN will be needed when this PR merges.
Fixes #2133
Added test assertions for the new field.
Create a deployment, open the deployment file, and then click Deploy. You should see the `logs_url` populated as soon as the Connect content item is created.
The TOML extension will continue to show that as an undefined field until the new schema is pushed.
=> Set logs URL immediately upon deployment

extensions/vscode/webviews/homeView/src/components/ActionToolbar.vue
A small refactor to make the `ActionToolbar` `data-vscode-context` more readable. 
Test out the `EvenEasierDeploy` more menu (`...`) - this is the only spot that `ActionToolbar` receives a Context Menu.
=> Make vscode context in ActionToolbar more readable

extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/DeployButton.vue, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/utils/hostConduit.ts
@dotNomad is looking into why we aren't applying the linting rules to the webview, but these came up because VSCode does (and we want it to).
This PR contains quick fixes to remove those throws.
In these cases, I simply output a console error and abort processing the function call. These conditions are all "assert-like" catches for us, so this approach should work fine.
Just a quick regression should be fine.
=> Remove some throws which were left in the web view

extensions/vscode/src/views/homeView.ts, internal/initialize/initialize.go, internal/initialize/initialize_test.go
This PR changes two things:
- when include or excluding a file in the extension UI a `/` is prepended to the file URI when it is sent to the API
- when a file is included in the created Configuration a `/` is prepended to them
This restricts the include to only the directory and _not_ its subdirectories avoiding some confusion when using the Project Files view.
Resolves #2159
Ensure newly created Configurations work as expected
Ensure that the include and exclude actions in the Project Files view work as expected
=> Default included files to the relative root dir

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/multiStepInputs/selectNewOrExistingConfig.ts, extensions/vscode/src/utils/names.ts
This PR introduces a new naming setup for configuration files where they are named after the provided title of the content.
The file names also include a short unique string of base 32 characters for example: `fastapi-simple-AU9Q` to avoid collisions with collaborations via Git.
Resolves #2067
The approach here was to avoid enumerating configurations and start using the title. To achieve file name safety a new dependency was brought in - [filenamify](https://github.com/sindresorhus/filenamify).
The random characters are created with `Math.random()` since we do not need cryptographic security on these. They then are converted from numbers to strings with the radix `32`. …
=> Use titles to name configuration files in addition to short hash

extensions/vscode/src/utils/files.ts, extensions/vscode/src/views/homeView.ts
Corrects usage to proper function for file paths. 
Fixes: #2175 
From the VSCode documentation: 
```
* The *difference* between {@link Uri.parse} and {@link Uri.file} is that the latter treats the argument
* as path, not as stringified-uri. E.g. `Uri.file(path)` is *not* the same as
* `Uri.parse('file://' + path)` because the path might contain characters that are
* interpreted (# and ?). See the following sample:
* ```ts
* const good = URI.file('/coding/c#/project1');
* good.scheme === 'file';
* good.path === '/coding/c#/project1';
* good.fragment === '';
*
* const bad = URI.parse('file://' + '/coding/c#/project1');
* bad.scheme === 'file';
* bad.path === '/coding/c'; …
=> Switch to properly use `Uri.file()` rather than `Uri.parse()`.

test/vscode-ui/test/helpers.ts, test/vscode-ui/test/specs/fastapi.spec.ts, test/vscode-ui/test/specs/nested-fastapi.spec.ts
Tests started failing last night because they look for the config name and check its contents. This PR uses a regex to find the filename opened in the editor and then checks the contents of that file.  
Tests are passing against this branch:
https://github.com/posit-dev/publisher/actions/runs/10599971513/job/29376369061
fixes: https://github.com/posit-dev/publisher/issues/2197
=> update tests to get the new config name since they are no longer static

internal/inspect/detectors/pyshiny.go, internal/inspect/detectors/pyshiny_test.go
This PR ensures that the entrypoint file for a Shiny Express app is included in the Files list. Since the entrypoint is in module:object format, the generic config generation wasn't including it.
Fixes #2137 
Add the entrypoint file in the `pyShinyDetector`.
Updated existing tests to verify the files list is correct.
Inspect a Shiny Express app, and verify that the entrypoint file appears in the Files list.
=> Add PyShiny entrypoint to Files list

extensions/vscode/src/utils/progress.ts, extensions/vscode/src/views/homeView.ts
This PR ensures that errors generated from fetching R or Python packages are caught to avoid creating uncaught exception logs in the debug console.
I plan to do a follow-up PR to merge `showProgressPassthrough` and `showProgress` and refactor other usages.
This should supersede #2183
The approach was to pass the awaited function as the callback for `window.withProgress`, and use the fact that `window.withProgress` returns the "thenable the task-callback returned.".
This avoids creating a new callback and thus the uncaught exception error.
To recreate the errors checkout `main` and open up the "Debug Console" while running VS Code in Extension Development Host mode.
- …
=> Passthrough callbacks with new `showProgressPassthrough`

extensions/vscode/src/multiStepInputs/newCredential.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/multiStepInputs/selectNewOrExistingConfig.ts, extensions/vscode/src/utils/progress.ts, extensions/vscode/src/views/homeView.ts
Follow-up to #2194 that refactors all `showProgress` usage to use the new passthrough callback return method to ensure that errors are caught.
=> Refactor `showProgress` to passthrough callback return

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/api/client.ts
Resolves #2176 
Brought in an HTML decoder which would decode the string that the agent encoded using the go package `html` (escapeString).
Performed this decoding for all responses that fail with a 500 error code, by updating the Axios client response interceptor. Only doing this for the response data field, as that is the only place it was applied on the agent within #2152.
ALSO determined that we were not outputting durations for error responses. I've gone ahead and included that change within this PR as well.
Easiest way to reproduce a 500 error is to invalidate a configuration file. For my testing, I changed the `[python]` section to be `[python2]`. Once you have …
=> Decode 500 error's data string

internal/initialize/initialize_test.go, internal/inspect/detectors/all_test.go, internal/inspect/detectors/html.go, internal/inspect/detectors/html_test.go, internal/inspect/detectors/pyshiny.go, internal/inspect/detectors/pyshiny_test.go, internal/inspect/detectors/quarto.go, internal/inspect/detectors/quarto_test.go
This PR ensures that we prepend the `/` to avoid accidentaly including files with the same name as the entrypoint in subdirectories for the configuration files we generate.
This is a follow-up to #2174 that applies this to all types of Deployments - HTML, Quarto, Shiny Express, etc
Resolves #2211 
=> Preprend slash in config files for all types

extensions/vscode/src/api/types/files.ts, extensions/vscode/webviews/homeView/src/components/views/projectFiles/TreeProjectFiles.vue, extensions/vscode/webviews/homeView/src/components/views/projectFiles/tooltips.ts, internal/bundles/matcher/match_list.go, internal/bundles/matcher/mock_match_list.go, internal/bundles/matcher/pattern.go, internal/bundles/matcher/walker.go, internal/bundles/matcher/walker_test.go, internal/services/api/files/files.go, internal/services/api/files/services.go, internal/services/api/files/services_test.go
This PR adds handling for permission errors during directory traversal.
Fixes #2135 
The `MatchingWalker` and `filesService` suppress permission errors.
Deny read permissions to files or directories in your project (`chmod 000 $PATH`).
* Directories that can't be read will show up as empty in the Project Files view. 
* Files that can't be read will show up in the Project Files view. If you exclude them, you can deploy without error. If you include them, an error will be raised during deployment.
This is similar to the VSCode file tree behavior.
=> Suppress permission errors

extensions/vscode/webviews/homeView/src/components/views/projectFiles/TreeProjectFiles.vue
This PR fixes the added decorator (the green A after files in the Project Files view) to only show if the file is new (not included in the last deployment) and included.
Previously any file that was new was being decorated.
Resolves #2218
=> Only show added decorator when file is new and included

extensions/vscode/webviews/homeView/src/components/views/projectFiles/TreeProjectFiles.vue
This PR adds an additional file decoration for files that were included in the last deployment, but are excluded for the next. They are now marked with a red `R` for removal.
The source control VS Code extension uses a red `D` for deletion, but that didn't feel quite right since the file is just being excluded (or removed from the next deployment).
<details>
</details> 
Resolves #2222
The approach here is extremely similar to the green `A` with a different `v-if`
To see this in action:
- make a deployment
- unselect files previously deployed in the Project Files view
=> Add decoration for removed files in Project Files

extensions/vscode/webviews/homeView/src/components/views/projectFiles/TreeProjectFiles.vue
This PR fixes the windows path comparisons between the Content Record's `file` list and the files we get from the files API.
Previously I was using `file.rel` which was doing comparisons like:
```
'subdir\\subsubdir\\newtext.txt' == 'subdir/subsubdir/newtext.txt'
```
Instead of 
```
'subdir/subsubdir/newtext.txt' == 'subdir/subsubdir/newtext.txt'
```
`file.rel` in our files API gives the relative path with the OS's separators where `file.id` gives the same string that we expect in our content records and configuration files.
With that corrected this should address the issue of decorators showing up or not showing up correctly on Windows.
Resolves #2112
=> Use `file.id` comparison to match content record files list

extensions/vscode/webviews/homeView/src/components/tree/TreeSection.vue
This PR adds a new optional prop to `TreeSection` allowing a codicon string to be passed. When passed the codicon will appear to the left of the title, and the right of the twisty for the section.
<details>
The icon is small to match the title font size, and is the same muted color. 
</details> 
=> Add support for optional codicon in TreeSection

extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/utils/names.ts
With #2182 configuration file names were named like `fastapi-simple-QSPH` based on the title of the content.
This PR uses the same 4 random, base32 string appending characters to create content record files - like `deployment-DEQ7` to avoid git conflicts with created deployments.
Resolves #1818
=> End deployment filenames with unique characters

internal/schema/schemas/config.toml, internal/schema/schemas/posit-publishing-schema-v3.json, internal/schema/schemas/record.toml
This PR adds `secrets` to our `posit-publishing-schema-v3.json` for Configuration files.
It is an array of strings to indicate the name (not value) of secrets that are available to be published alongside a deployment:
```
secrets = ['API_KEY', 'DATA_PASSWORD']
```
Resolves #2251
~This doesn't include changes to the Content Record, but will be added in a future PR.~
After a bit more work on this I realized that isn't necessary.
A lot of file changes you may expect are missing from this PR since `secrets` was already in our Frontend and Backend types for Configuration details. We just didn't specify them in the schema.
I did not increase the schema version for this since …
=> Add secrets to config schema

cmd/publisher/commands/deploy.go, cmd/publisher/commands/redeploy.go, internal/publish/bundle.go, internal/publish/check_configuration.go, internal/publish/create_deployment.go, internal/publish/deploy_bundle.go, internal/publish/publish.go, internal/publish/publish_test.go, internal/publish/r_package_descriptions.go, internal/publish/set_env_vars.go, internal/publish/update_content.go, internal/publish/validate.go, internal/services/api/api_helpers.go, internal/services/api/post_deployment.go, internal/services/api/post_deployment_test.go, internal/services/api/post_deployments.go, internal/services/api/post_inspect.go
Adding some more debug logs to the inspection and deployment areas of the backend.
Connected to #2153 
- Some new `log.Debug` calls within the inspection and deployment.
- Adding a logger instance to `defaultPublisher` to do logging calls easier across this instance methods.
Updated a few unit tests related to expected logging instances.
While inspecting and deploying, there should be more debug log lines in the output.
=> Adding some more debug lines to inspection and deployment

extensions/vscode/webviews/homeView/src/components/tree/TreeItem.vue, extensions/vscode/webviews/homeView/src/components/tree/TreeItemCheckbox.vue
In `TreeItem` and `TreeItemCheckbox` there was a height difference depending on if a description was rendered. This was not very noticeable unless the description was toggled causing a `1px` layout shift.
The reason this was occurring was due to the `line-height` set on the `span` element containing the description:
> On block-level elements in horizontal writing modes, it (`line-height`) specifies the preferred height of line boxes within the element, and on non-[replaced](https://developer.mozilla.org/en-US/docs/Web/CSS/Replaced_element) inline elements, it specifies the height that is used to calculate line box height.
`line-height` did not have any affect on the rendering of the description but did seem to adjust the height when that element was included in the DOM. Removing it fixed …
=> Avoid height changes in Tree Items due to `line-height`

extensions/vscode/src/api/resources/ContentRecords.ts
Nice and simple PR that adds the ability to send up the secrets in our `ContentRecords.publish()` method.
Part of #2251
=> Add optional secrets arg to publish method

extensions/vscode/webviews/homeView/src/components/CountBadge.vue, extensions/vscode/webviews/homeView/src/components/tree/TreeSection.vue
This PR adds a new prop `count` to `TreeSection` that enables showing a `CountBadge` similar to other sections in VS Code.
<details>
Note the "real" VS Code count badge in the Source Control section on the left, and the "fake" count badge on the right in the Secrets view.
</details> 
Part of #2252
=> Add support for count badge to TreeSection

extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/App.vue, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/DeployButton.vue, extensions/vscode/webviews/homeView/src/components/SidebarInput.vue, extensions/vscode/webviews/homeView/src/components/tree/TreeItem.vue, extensions/vscode/webviews/homeView/src/components/views/secrets/Secret.vue, extensions/vscode/webviews/homeView/src/components/views/secrets/Secrets.vue, extensions/vscode/webviews/homeView/src/stores/home.ts, extensions/vscode/webviews/homeView/src/style.css
This PR adds a new Secrets section to the Home view.
Some new features:
- Secret values present are sent up on Deploy and added as environment variables on Connect. If the env var is present it's value is overwritten
- When changing Deployments the provided Secret values are cleared
- When a successful Deployment occurs the provided Secret values are cleared
- When a Configuration is changed, but the Deployment stays the same, the shared Secrets keep their values in the UI
- The number of Secrets with values is displayed as a Count badge on the Secrets section header to help the user know what is going to be sent up
- When editing a Secret the input will be selected so all of the value is highlighted for easy overwrite (similar to the rename functionality in VS Code)
<details> …
=> Add Secrets view and deploy with Secrets to extension

cmd/publisher/commands/credentials.go, internal/accounts/account_list.go, internal/accounts/provider_credentials.go, internal/credentials/credentials.go, internal/credentials/credentials_test.go, internal/logging/logger.go, internal/services/api/delete_credentials.go, internal/services/api/delete_credentials_test.go, internal/services/api/get_credential.go, internal/services/api/get_credentials.go, internal/services/api/post_credentials.go, internal/services/api/post_credentials_test.go
PR introduces quite simple changes for CredentialsService to have it's own logging instance, allowing to have further logging calls within credentials operations.
This is an initial work for #1831
This PR adds a logger to `CredentialsService` which is now private - `credentialService` - such change for two reasons:
1. Continuity to #2153 - more debug logging where we are lacking
2. These changes help and are introductory work to #1831
Making credentials service private is to prevent panics, since `credentialsService` will call a logger instance internally, making the struct private and the interface and constructor public, forces consumers of this service to pass a logger. E.g:
```go
// The following would bring a panic, program will compile with no issues but with the risk of runtime …
```
=> Credentials service with a logger

package-lock.json, package.json
While investigating #2282 I ran `npm update` to up the root level npm packages.
This doesn't adjust the extension or webview packages which look to need some migration.
Prettier was upgraded, but no formatting was needed.
=> Update npm packages at root dir

extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json, extensions/vscode/webviews/homeView/src/HostConduitService.test.ts, extensions/vscode/webviews/homeView/vite.config.ts
Supersedes #2282 and #2302. This PR updates quite a few packages (using `npm update` so keeping major versions the same). This includes updates for Vite, Vue, rollup, and other related packages.
This PR also locks the version of Axios since minor versions have, and currently do break types when upgraded.
A note that after upgrading the packages I started to see a deprecation warning for `sass`
> Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
> More info: https://sass-lang.com/d/legacy-js-api
To fix this I followed the recommendation in the Vite documentation to
> use api: "modern-compiler" with `sass-embedded` package.
`sass-embedded` is an alternative to `sass` and instead of being JavaScript is a native Dart executable. So `sass` was …
=> Update npm packages for home view

extensions/vscode/webviews/homeView/src/components/views/secrets/Secrets.vue
Small change that hides the "Clear Values for all Secrets" button in the Secrets view until there are secrets with values to clear.
Resolves #2304
=> Only show clear secrets button when values present

internal/services/api/api_service.go, internal/services/api/get_config_secrets.go, internal/services/api/get_config_secrets_test.go
This PR adds a new API endpoint `GET /api/configurations/$NAME/secrets` that returns an array of Secrets in the named Configuration file.
Part of #2305
Test out the new endpoint testing in and out of multi-directory roots:
`http :9001/api/configurations/fastapi-simple-QSPH/secrets`
`http :9001/api/configurations/fastapi-simple-QSPH/secrets dir==fastapi-simple`
=> Add GET configuration secrets endpoint

internal/credentials/credentials.go, internal/credentials/credentials_test.go, internal/credentials/errors.go, internal/credentials/file.go, internal/credentials/file_test.go, internal/credentials/testdata/toml/goodcreds.toml, internal/credentials/testdata/toml/testdelete.toml, internal/credentials/testdata/toml/testset.toml
Incremental work pushed for #1831 
This PR adds a new credentials service and it's constructor, which will handle cases where a system keyring service is unavailable.
- `fileCredentialsService`
- `NewFileCredentialsService(log logging.Logger) (*fileCredentialsService, error)`
This new file credentials service is unplugged in this PR, meant to facilitate incremental review of the file credentials work.
A subsequent PR will be created pointing to this one (at least until this one is merged).
Main points of this new file credentials service:
- Has a setup step that runs within the constructor to verify if the `.connect-credentials` file exists, creates it when needed.
- Implements the methods of the existing credentials service that uses the keyring provider. To allow plugging it in and be …
=> File credentials service (unplugged at the moment)

internal/config/config.go, internal/config/config_test.go, internal/services/api/api_service.go, internal/services/api/post_config_secrets.go, internal/services/api/post_config_secrets_test.go
This PR adds a new API endpoint `POST /api/configurations/$NAME/secrets` that:
- takes an action and secret name similar to the POST files API
- returns a `configDTO` containing the `projectDir`, `configuration`, and `configLocation` for easy plug into our frontend store
Part of #2305
Test out the new endpoint:
- testing the add and remove action
- testing in and out of multi-directory roots
`http POST :9001/api/configurations/fastapi-simple-QSPH/secrets action=add secret=new`
`http POST :9001/api/configurations/fastapi-simple-QSPH/secrets action=remove secret=new`
`http POST :9001/api/configurations/fastapi-simple-QSPH/secrets action=remove secret=new …
=> Add POST configuration secrets endpoint

extensions/vscode/src/api/client.ts, extensions/vscode/src/api/resources/Secrets.ts, extensions/vscode/src/api/types/secrets.ts
Adds the `Secrets` resource and associated types to the `api` module in the extension to use the two new APIs:
- `GET /api/configurations/$name/secrets`
- `POST /api/configurations/$name/secrets`
Part of #2305
=> Add frontend Secrets API client resource

extensions/vscode/package.json, extensions/vscode/src/constants.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/components/views/secrets/Secret.vue
Adds the ability to remove a Secret name from the selected Configuration in the UI.
To do this you can right-click a Secret to bring up a context menu, similar to the removal of Credentials.
<details>
https://github.com/user-attachments/assets/f879e7fd-ebf7-4a28-a972-c7bc77609bf3
</details> 
Part of #2305
=> Add ability to remove a Secret name in the UI

extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/components/views/secrets/Secrets.vue
This adds a new `+` button to the Secrets view header which will prompt for a name and add that name as a Secret to the selected Configuration.
<details>
https://github.com/user-attachments/assets/8fe080f0-876d-4be9-aca8-f994b943eef7
</details> 
Resolves #2305
=> Add button to add a Secret to the config

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/components/tree/TreeSection.vue, extensions/vscode/webviews/homeView/src/components/views/Credentials.vue, extensions/vscode/webviews/homeView/src/components/views/PythonPackages.vue, extensions/vscode/webviews/homeView/src/components/views/RPackages.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
…ion when alerting
This PR adds action indicators to section headers to indicate that attention is needed.
resolves #2245 
Business logic that determined the display of actionable messages was moved into the central store for `EvenEasierDeploy.vue`, `Credentials.vue`, `RPackages.vue` and `PythonPackages.vue`. Existing logic was maintained, which was easy since each of these methods were already using the store to perform their computations.
`TreeSection.vue` component was updated to allow the specification of a `headerActions` prop, which is shown when the section is collapsed (vs. the `actions` prop which is only shown when the section is expanded. Also had to support …
=> Add contextual notification alert icons to section headers

cmd/publisher/commands/credentials.go, cmd/publisher/main.go, extensions/vscode/src/constants.ts, extensions/vscode/webviews/homeView/src/components/views/Credentials.vue, internal/accounts/account_list.go, internal/accounts/account_list_test.go, internal/accounts/provider_credentials.go, internal/credentials/credentials.go, internal/credentials/credentials_test.go, internal/credentials/errors.go, internal/credentials/file.go, internal/credentials/file_test.go, internal/credentials/keyring.go, internal/credentials/keyring_test.go, internal/services/api/api_errors.go, internal/services/api/delete_credentials.go, internal/services/api/delete_credentials_test.go, internal/services/api/get_credential.go, internal/services/api/get_credentials.go, internal/services/api/post_credentials.go, internal/services/api/post_credentials_test.go, internal/types/error.go
Full support for credentials persistence via a file `~/.connect-credentials`.
Following up the work done at #2308, this PR completes the feature by:
- Having a main credentials service constructor `NewCredentialsService`
- `NewCredentialsService` is called by endpoints that do credentials operations
- `NewCredentialsService` tries to:
-  set up the default system's keyring service, `NewKeringCredentialsService`
- falling back to file based credentials when there is no keyring available. `NewFileCredentialsService`
- This allows for different funtionality on credentials persistence to share the same interface for credentials operations `List(), Get(), Set(), Delete()`
**Screenshots of Workbench using the file backed credentials service**
- - [ ] …
=> File Credentials Support

extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/App.vue
This PR resolves the issue where API calls that depend on a valid configuration file are being called even if the configuration file is in error, which causes API failure notices to be displayed in VSCode.
Resolves #2323 
There are a number of API calls that we know depend upon a valid configuration file (as we are required to pass in the name of the active configuration file). I have added checks (where missing) into the methods in which we get the active configuration file and return immediately if the active configuration is in error. This removes the reported error message, which was occurring off of file watcher actions.
I have also updated the homeView to not …
=> Suppress calls to agent when active config is in error

CHANGELOG.md, docs/installation.md, docs/licenses.md, docs/vscode.md, extensions/vscode/CHANGELOG.md
This PR preps us for the release of `1.1.7` by:
- Updating the scripts to point to `1.1.7`
- Adds details for the release into the changelog (for the repo and the VS Code extension)
- Adds additional licenses
- Updates our VS Code Extension documentation to include info about:
- the new Secrets view
- the changes to the Credentials dotfile
- the new "updating previously deployed content" flow
- Updates outdated images
Resolves #2319
=> Update install scripts for 1.1.7

.github/workflows/contract.yaml, .github/workflows/nightly.yaml
When I updated the nightly tests to run against specific packages I made a couple mistakes.
1. Forgot to include the `package` job as a dependency
2. Used the amd build for macOS, GH Actions uses the arm build so it was causing failures
3. Added a fix for some flakiness around the fuzzbucket ssh key I create in an earlier step
All tests are now passing:
https://github.com/posit-dev/publisher/actions/runs/11145196437
=> Fixes for Nightly job

extensions/vscode/src/multiStepInputs/newCredential.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, test/vscode-ui/test/specs/extension.spec.ts, test/vscode-ui/test/specs/fastapi.spec.ts, test/vscode-ui/test/specs/nested-fastapi-configuration.spec.ts
A nice and simple reword for the Credential `multiStepInputs`:
From: Enter a Unique Nickname for your Credential.
To: Enter a unique nickname for this server and API key combination.
`Example: ` was also removed from the placeholder text to make it more similar to other VS Code inputs.
Resolves #2265
=> Reword Credential nickname prompt and placeholder

extensions/vscode/webviews/homeView/src/components/DeployButton.vue
This PR removes the disable state for the Deploy button when the configuration is in error.
There isn't anything preventing us from calling the Deploy API when this occurs. The warning is still present telling the user that their configuration is indeed in error, but now they can attempt a deploy and get an error message.
That looks something like this:
Our `ValidateTOMLFile` function will error when the Configuration doesn't match the schema, and has an error like the example above.
https://github.com/posit-dev/publisher/blob/7830e62c2bfe119d8d47c3dcc9dce19bacef5371/internal/schema/schema.go#L83
Resolves #2345 
=> Allow deploy when the config is in error

extensions/vscode/src/views/homeView.ts, internal/config/config.go, internal/config/config_test.go
This adds a small bit of validation code to our `addSecret` flow that checks to see if an environment variable already exists with the input name, and prevents the user from inputting it.
This is added at the VS Code input level, and on the API endpoint.
<details>
</details> 
Part of #2326
Automated tests were included for the Go code.
1. Add a Secret via the UI
2. Attempt to add a Secret via the UI that has the same name as an environment variable already in the Configuration
=> Check if an environment variable exists when validating added secret

extensions/vscode/webviews/homeView/src/components/DeployButton.vue, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
This PR adds a new error that disables deployment - similar to a missing credential error in style - when there are names shared in Environment and Secrets in the selected Configuration.
<details>
</details> 
The duplicated names are present in the error to make it easier to resolve, along with a link to edit the configuration similar to other errors.
Resolves #2326 
=> Show error and disable deployment when environment and secrets have duplicates

docs/installation.md
To address Jon's comment here:
https://github.com/posit-dev/publisher/pull/2332#discussion_r1787634361
This updates the `inotify` warning with a link to [VSCode File Watcher Issues doc](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues). While the doc doesn't explicitly state that `inotify` will need to be installed, it does mention that it is used for File Watching.
I had to manually install `inotify-tools` to get this working in my ubuntu22 VM.
Fixes: https://github.com/posit-dev/publisher/issues/1216
=> inotify linux link

extensions/vscode/src/api/types/events.ts, extensions/vscode/src/eventErrors.test.ts, extensions/vscode/src/eventErrors.ts, extensions/vscode/src/utils/errorTypes.ts, extensions/vscode/src/views/logs.ts, internal/clients/connect/client.go, internal/clients/connect/client_connect.go, internal/clients/connect/client_connect_test.go, internal/clients/connect/content.go, internal/clients/connect/mock_client.go, internal/clients/http_client/http_client.go, internal/clients/http_client/http_client_test.go, internal/events/cli_emitter.go, internal/events/events.go, internal/publish/publish.go, internal/publish/publish_test.go, internal/types/error.go, internal/types/error_test.go
**Main intent:**
Better error messaging on deployment errors due to bad content ID on deployment toml
**Common errors handled by this PR**
- The GUID does not match the content or does not exist - 404
- The user does not have permissions anymore to the content - 403
- Content is locked
- Unknown error
Fixes #2287 
Adding an extra step on the backend when deploying. Before building the bundle and doing any further operations, we will do a preflight check, trying to query the content target to validate that it can be reached, it exists and the user has permissions over it.
Returning an error with enough details to be handled by the extension code.
The changes are taking a similar approach to the http Axios errors but in this case these are messages sent by via SSE, so this is another area …
=> Deployment preflight errors due to bad content GUID

internal/bundles/bundle_test.go, internal/bundles/matcher/walker.go, internal/bundles/matcher/walker_test.go, internal/services/api/files/services.go, internal/util/symlink_walker.go, internal/util/symlink_walker_test.go
This PR aims to not pollute VSCode with notification errors about symlinks that do not exist. 
When a directory being watched by the Publisher extension is being modified by other software, there's the chance for symbolic links to be created to files that do not exist, like Emacs which creates symbolic files for unsaved modifications.
With this PR changes, we'll log the behavior and errors for symbolic links but won't show error notifications.
Fixes #2267 
Log symbolic link walking errors, do not bubble them up to the extension code as errors.
Updated unit tests accordingly.
Creating a symbolic link to a file that does not exist should show the `"Error following symlink" ... "no such file or directory"`  debug log but not notification error should show up.
E.g: 
`ln -s foo bar` should …
=> Be quiet for symlink walking errors

extensions/vscode/src/api/types/error.ts, extensions/vscode/src/commands.ts, extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
With this PR, configuration files which are unable to be parsed by the agent due to a TOML parsing error, will now indicate that the file was unable to be parsed and what line the error has been detected.
Resolves #2330 
The ConfigurationError object contains an AgentError. I have redefined an AgentError to be either an `AgentErrorTypeUnknown` or a `AgentErrorInvalidTOML`, with type guards defined for both.
When the active configuration has a TOML parsing error, the `EvenEasierDeploy` component will now display a brief statement as seen below. It includes an anchor to edit the configuration and the cursor will be positioned at the line and character location reported …
=> Show some details for a TOML parsing error

docs/configuration.md
Improved documentation for the `files` attribute in our Configuration files, being a little bit more specific about it using the gitignore syntax.
=> Add more specificity to git ignore files pattern documentation

test/vscode-ui/wdio.conf.ts
Pin vscode to 1.93.0 for tests for now. It seems webdriver.io has broken with the 1.94.1 release today.  This will be needed to unblock CI.
I'll keep reaching out to webdriver to see what we can do.
=> use 1.93.0 in vscode tests

extensions/vscode/src/views/homeView.ts, internal/config/config.go, internal/config/config_test.go, internal/config/types.go, internal/initialize/initialize_test.go, internal/services/api/get_configuration_test.go, internal/services/api/get_configurations_test.go, internal/state/state_test.go
This PR sets the the defaults for the `R` and `Python` structs for the Config after we fetch the details from the file.
Our schema defaults `package_manager` and `package_file` for both sections, but when doing a `GET /api/configurations/$name` we would get back empty strings for those values with a configuration file that looked like:
```
...
[r]
version = '4.3.1'
[python]
version = '3.8.5'
```
This PR avoids us from defaulting in the frontend and moving the onus to the backend to tell us how it interprets the Configuration
Resolves #2328
The error from #2328 was caused by:
https://github.com/posit-dev/publisher/blob/67706f071bff37b69e5e94bbb6ab4e521d25b31b/extensions/v …
=> Set R and Python Config defaults

.github/CODEOWNERS
This just removed @tdstein from the CODEOWNERS.
This fixes the issue where changes in `/internal` were only auto-requesting reviews from Taylor.
=> Consolidate CODEOWNERS

extensions/vscode/src/eventErrors.test.ts, extensions/vscode/src/eventErrors.ts, extensions/vscode/src/utils/errorTypes.ts, internal/initialize/initialize.go, internal/inspect/r.go, internal/publish/r_package_descriptions.go, internal/publish/r_package_descriptions_test.go, internal/types/error.go
This PR aims to stop showing or blocking the user on `renv.lock` file errors. Only showing the error when proceeding to deploy.
Fixes #2327 
**Screenshot of the new friendlier message**
Having a more structured and identifiable error to handle better the messaging when R packages cannot be scanned from the existing `renv.lock` file. Now logging out the errors as needed but not blocking the user until the `renv.lock` file scanning is absolutely required.
Updated and added unit tests as needed.
Having an empty `renv.lock`, you shouldn't see an `renv.lock` related error message until trying to deploy.
=> Be silent on renv.lock file errors until trying to deploy

internal/inspect/r.go, internal/inspect/r_test.go
…irst line.
Handle the case where the user has defined `R_HOME` in their environment. 
NOTE: The objective here is to determine the version of R based on the one that executes off of the path, NOT the one which may be at the `R_HOME` location.
Resolves #2343 
The existing code was only running regEx match against the first line in the output.
Fix simply loops over every line of the output and uses the first match.
Each line is logged as examined, which continues what was happening before (and helped us diagnose this so quickly).
Unit tests updated.
**Confirm the fix for the bug**
- You'll need to define the `R_HOME` environment variable in your base user profile (I …
=> R Version Detection: Loop over lines rather than just first line of 'R --version' output

extensions/vscode/webviews/homeView/src/components/views/secrets/Secret.vue
This changes the "Edit Value" codicon from `codicon-edit` to `codicon-symbol-string` to improve clarity that the action will add or edit a value, not edit the name of the secret.
https://github.com/user-attachments/assets/568ee04f-c557-43de-9a30-4ff11137ef32
=> Change edit secret value icon from edit pencil

internal/clients/connect/capabilities.go, internal/clients/connect/client.go, internal/clients/connect/client_connect.go, internal/clients/connect/client_connect_test.go, internal/clients/connect/mock_client.go, internal/publish/preflight_checks.go, internal/publish/publish.go, internal/publish/publish_test.go
Resolves #2375 - Locked Content Error during deployment not represented in Publisher log view
Also, as discussed, refactors this and a few other errors to be more consistent with other preflight errors.
The preflight checks for the content on the Connect server were not returning operation errors and were not interacting with the log used for the publisher log window (and associated event stream). This has been corrected.
To increase consistency, the preflight checks have been refactored with some renaming and movement. To summarize:
- rename publish.checkConfiguration to publish.preFlightChecks
- update connectClient.CheckCapabilities to have content target checks …
=> Change Locked Content Error to be compatible with publisher event stream

extensions/vscode/src/api/types/error.test.ts, extensions/vscode/src/api/types/error.ts, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, internal/clients/connect/capabilities.go, internal/clients/connect/client_connect.go, internal/clients/connect/client_connect_test.go, internal/publish/publish_test.go, internal/services/api/get_deployment_test.go, internal/services/api/post_test_credentials_test.go, internal/types/error.go, internal/types/error_test.go
This PR applies some presentational details for content that for some reason fails to start, this is only for content that has runtime.
- Showing a warning sign now, instead of an "x" icon that mistakenly suggested to be clickable
- The button reads as "View Content Logs" and directs to Connect content logs page.
Fixes #2206 
Just some presentational changes and checks for errored deployments.
Added some unit tests around the Agent Errors type guards
=> Messaging details for deployed content that runs with error

extensions/vscode/src/api/types/credentials.ts, extensions/vscode/src/api/types/error.ts, extensions/vscode/src/multiStepInputs/newCredential.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/utils/errors.test.ts, extensions/vscode/src/utils/errors.ts, internal/services/api/post_test_credentials.go, internal/services/api/post_test_credentials_test.go, internal/util/urls.go, internal/util/urls_test.go, test/vscode-ui/test/specs/error-no-config_creds.spec.ts, test/vscode-ui/test/specs/nested-fastapi-configuration.spec.ts
When prompting for a server URL, discover the actual server API address needed by iteratively removing path segments and retesting API key authentication.
PR also includes word change for server URL prompts.
Resolves #2001
Resolves #2371 
Given the URL string for the server (provided by the publisher), attempt to validate the combination of server address and API key by removing path segments from the end of the server URL, until we either are able to make a successful API key validated request or we run out of possibilities.
A URL utility method was created to return the possibilities. It strips off any query params and URL fragments before producing an array of server …
=> Add credential server URL discovery

docs/vscode.md, extensions/vscode/package.json, extensions/vscode/src/constants.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/components/views/RPackages.vue
Resolves #2403 
Removed ability to scan from HomeView. This eliminates the original error shown, which was exposed from invalid `renv` environment.
Consolidated some errors to show consistently, and then replaced scan button with anchor link to `renv` documentation.
Updated documentation.
Verify:
- verify that the scan button is gone from the R Package view
- verify normal publish functionality with a `renv.lock` file in place (and active `renv` environment)
- verify R Package view shows welcome view with new anchor w/ reference to `renv` doc, when package file is not present (missing or empty). Name of package file should match what is in config. Anchor should open …
=> Remove R Package Scan action

CHANGELOG.md, docs/installation.md, extensions/vscode/CHANGELOG.md, install-publisher.bash
Includes:
- Updates to the documentation to point to `1.2.0`
- No license file updates were needed
- An updated CHANGELOG for `1.2.0`
**Before Merging**
- Ensure the CHANGELOG is up to date if any additional issues have been merged
- Ensure this is the last PR merged before `1.2.0` is tagged.
=> 1.2.0 Release

extensions/vscode/README.md
This PR improves the README included in the extension bundle and what is seen on the VS Code marketplace, Open VSX Registry, and when looking at the extension in Positron or VS Code.
It includes an outline of the features provided and links to our documentation and issue board.
Resolves #2024
=> Improved extension README

test/setup/connect_setup.py
On to another fuzzbucket flakiness issue...  Hopefully this is the last fix.  Now when I try to install Connect, the server doesn't respond in time so I'm increasing the timeout. 
This particular failure looks like this:
https://github.com/posit-dev/publisher/actions/runs/11512824114/job/32065035359#step:6:56
We'll see CLI failures because we're trying to publish some newer content types to an old Connect version (2022.06.0) that hasn't been updated.  
This PR increases the retries and retry interval to give the box a little more time. 
=> Increase Fuzzbucket retries

docs/configuration.md, internal/bundles/manifest.go, internal/bundles/manifest_test.go, internal/config/types.go, internal/schema/schemas/posit-publishing-schema-v3.json
This PR adds the two rendering options for Jupyter available in the Connect manifest:
- `hide_all_input` which hides all of the input cells on render
- `hide_tagged_input` hides the input cells marked `hide_input` 
See the documentation for `rsconnect-jupyter` for more information: https://docs.posit.co/rsconnect-jupyter/usage/#hide-input
**After merging we will need to update the schema on the CDN.**
Resolves #2399
We already had the types for the Manifest, and were aware of these issues, but our Configuration didn't have a way to set / pass through those options.
Here I'm using the same technique for R, Python, and Quarto configuration settings to create the manifest. …
=> Support Jupyter hide options in Connect manifest

extensions/vscode/src/api/resources/ContentRecords.ts, extensions/vscode/src/api/types/contentRecords.ts
Super simple PR that adds a type and a method for the new `GET /api/deployments/$NAME/environment` introduced in #2412.
Part of #2365
=> Add frontend types for environment API endpoint

extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/src/watchers.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/views/secrets/Secret.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
This PR introduces a new feature for the Secrets view showing more detail based on the state of the content on Connect using [the Get environment variables API endpoint](https://docs.posit.co/connect/api/#get-/v1/content/-guid-/environment).
Now the Secret will be de-emphasized if it already has a value is on the server, and emphasized when an action needs to be taken or is currently being taken (for example setting a value) by the user.
Additional the codicons are improved showing:
- a warning when the Configuration has a Secret declared that is not on the server yet
- showing a cloud upload icon when a value is ready to be sent up
- showing a check mark when the server already the Environment Variable set
The tooltips are also improved for the 4 different states the Secrets can have. …
=> Improve Secrets view by reflecting server Environment Variable states

extensions/vscode/src/multiStepInputs/multiStepHelper.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/utils/errorTypes.test.ts, extensions/vscode/src/utils/errorTypes.ts, internal/inspect/python.go, internal/inspect/python_test.go, internal/services/api/post_inspect.go, internal/services/api/post_packages_python_scan.go, internal/services/api/post_packages_python_scan_test.go, internal/types/api_errors.go, internal/types/api_errors_test.go, internal/types/error.go, internal/types/error_test.go
PR with the work to show a message warning the user about Python not available in the system as the reason to not be able to scan requirements or generate a deployment configuration.
Such message is shown, when not having a Python executable available, and when:
- Opening a directory in the IDE that can be easily identified as a Python project
- Trying to create a new deployment
- Trying to scan and generate a requirements.txt on a existing deployment (this is an edge case since the user cannot create a new deployment without Python, getting to this state should be fairly uncommon)
**Screenshot**
Identify and return a well known error when trying to get a Python …
=> Warning message for missing Python executable

extensions/vscode/src/eventErrors.test.ts, extensions/vscode/src/eventErrors.ts, extensions/vscode/src/utils/errorTypes.ts, internal/inspect/dependencies/renv/manifest_packages.go, internal/inspect/dependencies/renv/manifest_packages_test.go, internal/publish/r_package_descriptions.go, internal/publish/r_package_descriptions_test.go, internal/types/error.go
PR introducing some changes to stop hiding valuable error details when reading renv lockfile.
Instead of always displaying the message, `"Could not scan R packages from lockfile: renv.lock"`, we now allow some more details to be shown to the user related to the error in question.
**Screenshot of mismatching package version when reading renv.lock**
Created a couple known agent errors to share more details with the user. Also, we are now providing some more error specifics for unrecognized renv.lock reading errors.
Created and updated unit tests as needed.
More details about reading the renv.lock file can be seen when:
=> Stop hidding details for renv lockfile reading errors

extensions/vscode/.eslintrc.json, extensions/vscode/src/multiStepInputs/newDeployment.ts, internal/initialize/initialize.go, internal/initialize/initialize_test.go
This PR fixes two things:
1. When an `type="unknown"` deployment is created the entrypoint could be blank when we reach `normalizeConfig`, which would cause the entrypoint field to be missing from the Configuration and the `files` array to only contain a `/`
2. When we create a new deployment / configuration combo, if the Configuration we create is invalid (read `type="unknown"`) the API calls to update the file lists with the Posit deployment record / configuration file were failing
The API calls were failing because when we get a `Config` from a file we validate said file before decoding it:
https://github.com/posit-dev/publisher/blob/fa07fcf2c8ce07083676118228a02597dbcecd01/internal/config/config.go#L63
This makes sense, we have to have a valid file to get a valid `Config`, but the …
=> Handle potential errors during new deployment flow

internal/clients/connect/client_connect.go, internal/clients/connect/client_connect_test.go, internal/schema/schemas/posit-publishing-schema-v3.json
This PR does two things:
- Adds `type = 'unknown'` to our schema making it a valid option in our Configuration files
- Allows changing the type from `unknown` to something else and re-deploying
- Changing types if the previous type is not unknown is still invalid
With `type = 'unknown'` now passing schema validation for our Configuration files, when Config has that type:
- We lose the sidebar warning showing the user that the config is in error
- We lose TOML validation warnings if the user is using an extension like [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml)
- Actions like including or excluding files can now be done
- This addresses the trade off introduced in #2422 where `.posit` files couldn't be added automatically to the …
=> Allow `type: 'unknown'` in our Configuration schema

internal/clients/connect/client_connect.go
This PR changes our behavior in our pre-check comparing the App Mode on Connect and the Content Type we are trying to deploy.
Previously we compared the Content Type from our Config with the AppMode converted to a Content Type. With the introduction of the `quarto` and `quarto-static` types both leading to the same AppMode this comparison didn't quite work.
This changes the check to compare AppModes specifically since that is what truly can or cannot change, and handles our deprecated `quarto` type much better.
=> Compare AppMode in pre-check not ContentType

CHANGELOG.md, docs/installation.md, extensions/vscode/CHANGELOG.md, install-publisher.bash
This PR sets up the release of `1.4.0`:
- Updates the documentation and script to point to `1.4.0`
- Checks for license updates (none were needed for this release)
- Updates the CHANGELOGs for `1.4.0`
=> 1.4.0 Release

.github/workflows/release.yaml
Our release GitHub action uses version 1 of [`softprops/action-gh-release`](https://github.com/softprops/action-gh-release) we can update it to version 2 to avoid the deprecated Node.js version warning:
> [release](https://github.com/posit-dev/publisher/actions/runs/11826395875/job/32952545635)
The following actions use a deprecated Node.js version and will be forced to run on node20: softprops/action-gh-release@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
See this run for an example of the warning: https://github.com/posit-dev/publisher/actions/runs/11826395875
Reading [the release notes for `softprops/action-gh-release`](https://github.com/softprops/action-gh-release/releases) it doesn't look like …
=> Update `softprops/action-gh-release` to version 2

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json
A nice and simple `npm update` with a few touch-ups:
- Sets `axios` to `1.7.4` in the extension to match the version in the webview to ensure the package is the same across our repo
- Upgrades `@vue/tsconfig` to `^0.6.0`
- Locks TypeScript below `5.6.0` for the VS Code extension due to compilation failures from dependencies
=> Update npm packages

.husky/pre-commit
Simple change to our husky pre-commit hook to use the new format from [`v9.0.1`](https://github.com/typicode/husky/releases/tag/v9.0.1).
This prevents a deprecated message from appearing, and is a bit faster ⚡
=> Remove deprecated part of husky pre-commit hook

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/ports.ts, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json
This updates our `get-port` dependency for our extension to the latest, and removes it from the home view since it is not used there.
=> Update `get-port` dependency

extensions/vscode/src/actions/showAssociateGUID.ts, extensions/vscode/src/api/client.ts, extensions/vscode/src/api/types/error.ts, extensions/vscode/src/api/types/events.ts, extensions/vscode/src/eventErrors.test.ts, extensions/vscode/src/events.ts, extensions/vscode/src/multiStepInputs/multiStepHelper.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/multiStepInputs/selectNewOrExistingConfig.ts, extensions/vscode/src/test/suite/extension.test.ts, extensions/vscode/src/types/messages/conduit.ts, extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/utils/config.ts, extensions/vscode/src/utils/errorEnhancer.ts, extensions/vscode/src/utils/errorTypes.test.ts, extensions/vscode/src/utils/errorTypes.ts, extensions/vscode/src/utils/errors.test.ts, extensions/vscode/src/utils/errors.ts, extensions/vscode/src/utils/files.ts, extensions/vscode/src/utils/variables.ts, extensions/vscode/src/utils/webviewConduit.ts, extensions/vscode/src/views/deployProgress.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/src/views/logs.ts, extensions/vscode/src/watchers.ts
This PR is a follow-up to #2440 that addresses all of the new rules that are failing.
Resolves #1293
Rather than change every `any` I figured we could make a follow-up issue to remove the `// eslint-disable-next-line @typescript-eslint/no-explicit-any` added here since those are a bit complex.
The work I did do here that wasn't auto-fixed was removed the async promise executors. To see why this is recommended I suggest reading the `no-async-promise-executor` rule docs: https://eslint.org/docs/latest/rules/no-async-promise-executor
Test the changed code in the following flows:
- New Deployment flows
- Selecting a New or Existing Config
- The home view's …
=> Address ESLint errors from recommended plugins

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json
This PR updates our `glob` dependency.
The major release was used to drop support for Node versions before 20. Our repo already uses Node 20, so that was quite easy.
Due to this update we can also upgrade to TypeScript 5.6 across packages without `tsc` errors.
=> Update `glob` dependency

extensions/vscode/package-lock.json, extensions/vscode/package.json
Quick follow-up to #2443, updating `@eslint/js` to the latest version to match the `eslint` version.
=> Update `@eslint/js` to latest

.gitignore, .vscode/launch.json, CONTRIBUTING.md, extensions/vscode/CONTRIBUTING.md
Adds a `.vscode/launch.json` config for launching the Go API. In addition adds some documentation how to debug both the Go code, and the extension alongside it.
It is all a little manual at the moment, but it is at least a start.
=> Add Go launch.json and CONTRIB docs

extensions/vscode/package.json, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/stores/home.ts, extensions/vscode/webviews/homeView/src/utils/hostConduit.ts
Somehow, we overlooked that the code within the `webviews/homeView/src` was not being scanned by ESLint. I discovered it while working on the files within VSCode (which was configured to run the ESLint configuration on the homeView files.
This PR implements a very quick change to add that scanning to the existing `lint` script within the extension's `package.json` file, as well as resolve the discovered issues once it has been run.
No impact to users.
=> Update extension linting to include webview source

.github/CODEOWNERS
Simple change that removes @kgartland-rstudio from `CODEOWNERS`
=> Remove Kevin from CODEOWNERS

extensions/vscode/src/views/homeView.ts
This PR fixes an issue where the last selected deployment does not populate properly on the extension UI when initializing.
The cause of this issue was introduced at commit [d8eb18a](https://github.com/posit-dev/publisher/commit/d8eb18ab02c5ec3baa4138416c85fe3bbab1de45), such commit introduced two main changes:
1. Removal of an event bus
2. Moving logic from the `homeView` to `PublisherState`
Being the second change the cause of this problem, ignoring that a couple state method calls were still required to build up cached data that was used to display the last selected deployment.
Fixes #2459 
Went through the changes that caused this issue, looking for the area where …
=> Fix loading last selected deployment

CHANGELOG.md, docs/installation.md, docs/licenses.md, extensions/vscode/CHANGELOG.md, install-publisher.bash
This PR sets up the release of `1.6.0`:
- Updates the documentation and install script to point to `1.6.0`
- Checks for license updates (there were some this time)
- Updates the CHANGELOGs for `1.6.0`
=> 1.6.0 Release

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
Changes the chevron icon used in the sidebar for deployment selection to `codicon-chevron-right` from `codicon-chevron-down`
<details>
</details> 
<details>
</details>
=> Use chevron-right for deployment select

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/style.css
Nice and simple PR that de-emphasizes the "Deployment" label for our deployment select. This is done by:
- lowering the font size to `11px` from `13px` to match the VS Code sidebar header
- uses `--vscode-sideBarSectionHeader-foreground` color rather than the default
<details>
</details> 
<details>
</details>
=> De-emphasize deployments select label

extensions/vscode/webviews/homeView/src/components/QuickPickItem.vue
This PR emphasizes the selected deployment content title in the sidebar by bolding the text (with `font-weight: 600`) and adding a small amount of `padding-bottom` to separate it from the server and entrypoint details below it.
<details>
</details> 
<details>
</details>
=> Emphasize select deployment title

.github/workflows/home-view-unit-test.yaml, extensions/vscode/webviews/homeView/.gitignore, extensions/vscode/webviews/homeView/CONTRIBUTING.md, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json, extensions/vscode/webviews/homeView/vite.config.ts
This PR enables `coverage` for our home view Vitest suite. Coverage can be seen when running vitest (`npm test`).
Vitest has a handy feature [`coverage.thresholds.autoUpdate`](https://vitest.dev/config/#coverage-thresholds-autoupdate) which will update the `vite.config.ts` with improved threshold numbers when `vitest` runs.
This also sets up failures in CI if:
- Coverage thresholds are not met
- Coverage thresholds in the config need to be updated
Both of those CI flows have been tested in this PR.
Resolves #2488
The approach was to enable coverage for Vitest, and add CI checks to ensure that our current thresholds are met.
=> Enable coverage for home view Vitest

extensions/vscode/webviews/homeView/src/components/tree/TreeItemCheckbox.vue, extensions/vscode/webviews/homeView/src/components/views/projectFiles/ProjectFile.vue, extensions/vscode/webviews/homeView/src/components/views/projectFiles/tooltips.test.ts, extensions/vscode/webviews/homeView/src/components/views/projectFiles/tooltips.ts, extensions/vscode/webviews/homeView/src/style.css, extensions/vscode/webviews/homeView/vite.config.ts
This prevents the user from unchecking the entrypoint checkbox (and therefor removing the entrypoint from the `files` attribute in their configuration).
The configuration can still be edited by hand, but the sidebar no longer allows getting into this bad state.
Part of #1493 
The user will no longer be able to uncheck the entrypoint's checkbox.
Ensure that the entrypoint, no matter the details in the configuration, can be unchecked.
Checking the entrypoint checkbox should still be available if the configuration is manually edited and the entrypoint needs to be added.
=> Disable entrypoint checkbox in Project Files view

extensions/vscode/src/api/resources/Credentials.ts, extensions/vscode/src/state.ts, extensions/vscode/src/utils/errorTypes.ts, internal/credentials/errors.go, internal/credentials/file.go, internal/services/api/reset_credentials.go, internal/services/api/reset_credentials_test.go, internal/types/api_errors.go, internal/types/error.go
This PR adds a new `AgentError` that bubbles up if operations in the backing-up of the credential file fail, showing the user the message so they may take action on it.
Resolves #2513
Now a notification will be shown with the specific error that occurred when backing up a credential file, with an error code that we can do more with in the future.
Automated tests were added to ensure that the correct data is sent back when the reset API errors.
Ensure that the error bubbles up via the API, is shown as a notification, and works in Workbench.
=> Show error message if backing up credential file fails

.vscode/launch.json, extensions/vscode/.vscode/launch.json, extensions/vscode/CONTRIBUTING.md, extensions/vscode/src/extension.ts, extensions/vscode/src/services.ts
… of the UX and the agent
This PR updates the launch configuration for the vscode extension, to have two targets:
- `Debug with internal API agent`
- `Debug with external API agent on 9001`
The first one maintains the functionality we had before, but the second one supports the ability to launch the VSCode extension so that it expects there is an external (independently managed) API agent at port 9001.
`services.ts` has been updated to implement this functionality, but by default, will continue its prior behavior of managing the agent process itself. The functionality is protected by also checking that it has been launched in development mode so that we will not have this functionality leak out to customers.
I have updated the `extensions/vscode/CONTRIBUTING.md` file to reflect these …
=> Simplify debugging the agent and the extension at the same time (full-stack)

CHANGELOG.md, docs/installation.md, docs/licenses.md, extensions/vscode/CHANGELOG.md, install-publisher.bash
This PR sets up the release of `1.8.0`:
- Updates the documentation and install script to point to `1.8.0`
- Checks for license updates (there were some this time)
- Updates the CHANGELOGs for `1.6.0`
=> 1.8.0 Release

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/style.css, extensions/vscode/webviews/homeView/vite.config.ts
This PR updates the design of the last deployment alerts in the sidebar.
<details>
</details> 
<details>
</details> 
It uses a simpler border on the left giving us slightly more room in the horizontal space. It also colorizes the icon and border using the `--vscode-list-warningForeground` variable from the user's selected theme.
Users will see a colorized warning matching other aspects of the VS Code UI. They will be able to fit slightly more text on the horizontal reducing a little of the vertical push that they experience with deployment alerts.
=> Update design for last deployment alerts

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/style.css
This PR uses a new VS Code `descriptionForeground` to deemphasize the last deployment alert descriptions. The links inside of those descriptions are un-affected and will use the link color as normal.
<details>
</details> 
<details>
</details> 
The design more accurately reflects the emphasis we want to put on parts of the sidebar.
=> Deemphasize last deployment alert descriptions

extensions/vscode/src/events.ts, extensions/vscode/src/state.ts, extensions/vscode/src/views/deployProgress.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/vite.config.ts
Resolves: https://github.com/posit-dev/publisher/issues/2179
This PR contains follow-on changes to https://github.com/posit-dev/publisher/pull/2522. These changes have been separated by request to facilitate reviews in progress.
This PR addresses:
- removing the  flash of success status when canceling a deployment.
- Also fixed filtering to include some log messages from connect which had the local ID value in snake_case rather than camelCase. This suppresses a message from the Connect server which occurred when a second redeployment was progressing while the original, cancelled deployment was still processing.
=> Follow-on #2 for dismissed deployment support PR

.github/workflows/home-view-unit-test.yaml, extensions/vscode/webviews/homeView/vite.config.ts
This PR sets the `coverage.thresholds.autoUpdate` feature of `vitest` to `false` to avoid off by `0.01` coverage reporting errors.
=> Disable vitest thresholds `autoUpdate`

extensions/vscode/src/events.ts, extensions/vscode/src/views/deployProgress.ts, extensions/vscode/src/views/logs.ts, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
Change term from "Canceled" to "Dismissed" for the display status when the user has dismissed a deployment in progress. The notification which indicates that the deployment has been dismissed now shows as an informational message rather than an error message (the icon has changed).
With these changes, the UX displays the following when the user has clicked cancel on the deployment progress indicator:
=> Rewording "canceled" to "dismissed" and show notification as an informational message

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/style.css
This PR changes the structure and CSS of the in progress summary to be more similar to our other states - cancelled, successful, failed.
It unifies some of the CSS and markup to accomplish this so the vertical spacing and font-weight do not change across those summaries.
<details>
<summary>Preview Video</summary>
https://github.com/user-attachments/assets/2c2e569e-27c6-4908-b1ad-dfdfcc114448
</details> 
Notice how the vertical space between the title (progress ring) and the line above no longer change.
Resolves #2531 
=> Use the same structure and spacing for deployment summaries

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/components/QuickPickItem.vue
This PR adds icons next to the details in the deployment selection `QuickPickItem` component.
Specifically:
- the `server` codicon next to the Credential indicating the Connect Server the deployment will be going to 
- the `file` codicon next to the entrypoint file name
If you have an alternative suggest the list of codicons can be found here: https://microsoft.github.io/vscode-codicons/dist/codicon.html
<details>
</details> 
<details>
</details> 
Resolves #2483
The approach here was to support both strings (as we did before) and the new `IconDetail` object in the `QuickPickItem` `details` prop. Now that it supports …
=> Use icons with deployment selection details

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
This PR adds a new warning if the selected configuration has `type = 'unknown'` now that it is a valid type in the schema due to the work in #2423.
<details>
</details> 
I'm very open to suggestions regarding the text for the warning.
Resolves #2515 
When a selected configuration has `type = 'unknown'` the user will now see a helpful warning (similar to our others like duplicate environment variable names warning).
This can occur either through a manual change, but also if inspection isn't able to reason about the `type` and the initial configuration defaults to `type = 'unknown'`.
=> Add warning if selected config has `type = 'unknown'`

docs/index.md, docs/troubleshooting.md, extensions/vscode/src/utils/window.ts, extensions/vscode/src/views/logs.ts
This PR adds:
- a new Troubleshooting document linked from our `docs/index.md`
- The start of this document includes information for how to address the "Unrecognized app mode" error during deployment.
- a change to the `window.showErrorMessage` call on `publish/failure` to include a new "See **Troubleshooting docs** for help."
- The **Troubleshooting docs** text will link to the new troubleshooting document.
<details>
</details> 
Resolves #2476
I only included the troubleshooting link at our `window.showErrorMessage` call from `publish/failure` as opposed to always showing the Troubleshooting link because the only content in our …
=> Add troubleshooting link to documentation when `publish/failure` occurs

extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/src/components/tree/TreeItem.vue, extensions/vscode/webviews/homeView/src/components/tree/TreeItemCheckbox.vue
Simple PR that runs `npm upgrade` in the homeView package. This supersedes #2547 to capture the upgrade of `vite`
=> Run npm upgrade in homeView package

internal/schema/schemas/draft/posit-publishing-record-schema-v3.json, internal/schema/schemas/posit-publishing-record-schema-v3.json
I noticed that with the changes in #2522 that deployment files were showing schema errors through Even Better TOML. I didn't get errors when using Publisher, but the JSON schema was saying that `""` wasn't a `date-time`.
This allows the `dismissed_at` attribute be either an empty string or a `date-time`.
=> Allow empty string for `dismissed_at` in schema

CONTRIBUTING.md
A simple PR that updates our `CONTRIBUTING.md` document to include a tip to clear the Even Better TOML extension cache.
=> Add tip to clear Even Better TOML schema cache

docs/troubleshooting.md
This PR makes a few changes to the troubleshooting doc introduced in #2546. Some passive voice was changed to active, and the two sections under "Unrecognized app mode" have been made more clear.
=> Improve troubleshooting doc from feedback

extensions/vscode/webviews/homeView/src/components/views/projectFiles/ProjectFile.vue, extensions/vscode/webviews/homeView/src/components/views/projectFiles/tooltips.test.ts, extensions/vscode/webviews/homeView/src/components/views/projectFiles/tooltips.ts
This PR disables the checkbox for R and Python package files in the Project Files view, as well as includes a new tooltip when this is the case. It works very similar to #2487 
Part of #1503
Users can no longer un-check package files' checkboxes in the Project Files view - they can still check them to include the file if they are not included.
New automated tests are included for the new tooltip.
Ensure that the R and Python package files, no matter the details in the configuration, can be unchecked.
Checking the checkbox for the file should still be available if the configuration is manually edited and the package file needs to be added.
=> Disable `ProjectFile` checkbox when it is a package file

extensions/vscode/src/eventErrors.ts, extensions/vscode/src/utils/errorTypes.ts, extensions/vscode/src/utils/window.test.ts, extensions/vscode/src/utils/window.ts, extensions/vscode/src/views/deployHandlers.test.ts, extensions/vscode/src/views/deployHandlers.ts, extensions/vscode/src/views/logs.ts, internal/inspect/dependencies/renv/manifest_packages.go, internal/inspect/dependencies/renv/manifest_packages_test.go, internal/interpreters/r.go, internal/interpreters/r_mock.go, internal/interpreters/r_test.go, internal/publish/r_package_descriptions.go, internal/publish/r_package_descriptions_test.go, internal/types/error.go, internal/types/error_test.go
PR with the goal to provide immediate help to users when `renv` errors show up while trying to deploy.
Common scenarios that it handles, providing the option within the error message to set it up easily:
1. No `renv` installed at all. Installs `renv` and runs `init`.
2. `renv` is installed but project requires `init`, we do the `init` for the user.
3. `renv` environment exists, but lockfile does not. We help with `snapshot`.
For any other case outside the common and known issues, we provide the user with guidance and set up the `renv::status` command to get more information.
https://github.com/user-attachments/assets/d66c93b9-57d8-48ae-a2af-a22a55f06518
Resolves #2543  …
=> `renv` setup -  Provide users with an easy solution for renv errors

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
This PR changes the behavior around the "View Content" button to only show it if we have a URL to go to. Previously we checked if the deployment wasn't a pre-deployment, but a failed deployment will not have a valid ID or links.
Resolves #2373
If an error occurs during the deployment that causes the deployment to no longer be a pre-deployment, but still doesn't have an ID the "View Content" button no longer is shown.
=> Only show the view content button with a valid link

extensions/vscode/.vscodeignore
This PR adds a few directories and files to the `.vscodeignore` file which prevents those files being bundled into the extension:
- A `CONTRIBUTING` doc
- A `vitest` and `fantasticon` configuration file
- And the `coverage` directory in case that ever sneaks in during the CI
To see what files are bundled you can go to the `extensions/vscode` directory and run: `npx vsce ls` which will utilize the `vscode:prepublish` script and show what files are included.
After this PR the list is:
```
assets/img/posit-publisher.png
assets/walkthroughs/activate-extension.png
assets/walkthroughs/create-new-deployment.png
assets/walkthroughs/deploy.png
assets/walkthroughs/edit-configuration.png
assets/walkthroughs/open-folder.png
assets/walkthroughs/visit-content.png
bin/publisher
CHANGELOG.md …
```
=> Add additional files and directories to `vscodeignore`

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json, package-lock.json, package.json
This upgrades several dependencies across our three primary packages - the base package, the VS Code extension, and the home view.
This includes upgrades to:
- `esbuild` to bundle the extension
- `prettier` and `eslint-config-prettier`  for code formatting and compatibility with ESLint
- `mocha` for VS Code testing
- `entities` for HTML5 decoding
- `jsdom` for testing the home view
A few packages were not upgraded:
- `@types/node` wasn't upgraded since VS Code is still using Node 20 via Electron
- `eventsource` had some breaking changes. A follow-up issue was made: https://github.com/posit-dev/publisher/issues/2572
- `vite` and `vitest` were not upgraded as they had a migration. That will be a separate PR
- `axios` has a TypeScript compilation issue with `AxiosRequestConfig` typing we do …
=> Upgrade dependencies

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json, extensions/vscode/webviews/homeView/vite.config.ts
This PR upgrades dependencies around Vite 6.0:
- `vite` itself
- `vitest` for testing
- `@vue/tsconfig` for an updated TypeScript Vue configuration file
- `@vitest/coverage-v8` for our coverage reporting
The approach here was to upgrade all of the dependencies at once and work my way through the [Vite 5 -> 6 Migration Guide](https://vite.dev/guide/migration).
I ran our vitests to make sure those still passed, and ran the extension testing the functionality.
Pull this down and check that CLI tooling like `just` and tests behave as expected.
Run the extension itself and test the behavior has not been impacted by upgraded dependencies.
=> Upgrade Vite and Vitest

extensions/vscode/webviews/homeView/src/components/views/PythonPackages.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
Resolves #2529 
Bug in variable usage; Code was evaluating a reference rather than its value.
Bug fixed! Will now see:
with it showing properly after adding a section
=> Show Python welcome view when python not a dependency

CONTRIBUTING.md, go.mod, go.sum, vendor/golang.org/x/net/LICENSE, vendor/golang.org/x/sys/windows/dll_windows.go, vendor/golang.org/x/sys/windows/syscall_windows.go, vendor/golang.org/x/sys/windows/types_windows.go, vendor/golang.org/x/sys/windows/zsyscall_windows.go, vendor/modules.txt
This PR upgrades two Go dependencies:
- ` golang.org/x/crypto` to 0.32.0
- `golang.org/x/net` to 0.34.0
The approach here was just to use `go get <dependency>@latest` and then `go mod vendor`.
Pull this down and check that CLI tooling like just and tests behave as expected.
Run the extension itself and test the behavior has not been impacted by upgraded dependencies.
=> Upgrade Go crypto and net dependencies

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json, package-lock.json
This resolves two alerts around our `axios` and `esbuild` version.
Supersedes #2597 and #2593
- Ran `npm upgrade` in the three packages we have (root, extension, and homeview)
- Upgraded `esbuild` using `npm install esbuild@latest` since it was `0.24.2 -> 0.25.0`
- The `esbuild` changelog doesn't contain anything that stood out as needed changes: https://github.com/evanw/esbuild/blob/main/CHANGELOG-2024.md
- Upgraded `axios` manually using `npm install axios@latest --save-exact` since Axios sometimes has problems with minor version increases
I tested the build step individually and across the repo.
Pull down the changes and ensure that normal build, debugging flows work …
=> Upgrade axios, esbuild, and other dependencies

extensions/vscode/CHANGELOG.md, extensions/vscode/package.json, extensions/vscode/src/authProvider.ts, extensions/vscode/src/extension.ts, extensions/vscode/src/servers.ts, extensions/vscode/src/state.test.ts, extensions/vscode/src/state.ts, extensions/vscode/src/views/homeView.ts
This commit adds an [`AuthenticationProvider`][0] implementation for existing Publisher credentials. This has a few advantages:
1. It makes the Publisher's credentials feel more "native" to VS Code and Positron, in that they appear in the Accounts UI and can leverage the editors' native Sign Out flow.
2. It introduces a well-established way for other extensions to access Publisher credentials: via the helpers in the `authentication` namespace (provided that the user specifically designates a given extension as "trusted", which I think is quite a nice feature).
Demo:
[Screencast from 2025-03-24 08:37:14 AM.webm](https://github.com/user-attachments/assets/fbe87e8a-5850-48ef-98e4-9bfcb432a81d)
[0]: https://code.visualstudio.com/api/references/vscode-api#AuthenticationProvider
- - [ ] Bug Fix …
=> Expose Publisher credentials via an AuthenticationProvider

CHANGELOG.md, extensions/vscode/package.json, extensions/vscode/src/extension.ts
This PR provides the publisher extension with the functionality to support running within Restricted Mode. When in restricted mode, all publishing functionality is hidden, with only a button made available to manage the trust of the workspace (which is common with other extensions).
If and when the workspace is trusted by the user, the extension will commence its initialization. If the workspace is untrusted once again, the publisher returns to its restricted view.
Resolves #2611 
At activation, the code will check if it is being activated in trusted mode or not. If it is, it proceeds with initialization. If restricted mode is active instead, it registers an event …
=> Handle workspace trust states

internal/schema/schemas/config.toml
The sample config provided with the configuration schema was not updated when `required_python` was added to the configuration schema. This simple change updates the file. Once it has been merged, the S3 copy of this file should be updated as well.
Reference: `/CONTRIBUTING.md` section: `Schema Updates`.
=> Updating sample config.toml (was not updated as part of corresponding schema update)

CHANGELOG.md, docs/installation.md, extensions/vscode/CHANGELOG.md, install-publisher.bash, internal/schema/schemas/record.toml
ARM version of Mac extension is not showing up on OpenVSX. 
Unable to remove version 1.12.0, so we've decided to update to a patch version to attempt to fix it.
No significant changes, other than those related to the release.
=> Publish Release 1.12.1

CHANGELOG.md, extensions/vscode/CHANGELOG.md, extensions/vscode/src/api/types/configurations.test.ts, extensions/vscode/src/api/types/configurations.ts, extensions/vscode/src/test/unit-test-utils/factories.ts
Fix for default interpreter data creating `renv.lock` file when scanning Python dependencies, instead of `requirements.txt`
Fixes #2639 
Add the proper default interpreter values for Python configurations.
Users hitting the `Scan` button in Python should get a proper `requirements.txt` file now
Added new unit-tests to cover the methods handling the interpreter defaults.
1. Open a workspace within Visual Code which has a python file present, can be done with the sample project: `test/sample-content/fastapi-simple` from the publisher repo.
2. Switch to Publisher
3. Create new deployment and select `app.py` as the entrypoint.
4. Expand the python section
5. Click `scan`
A …
=> Fix python scan creating renv.lock file

.github/workflows/agent.yaml, internal/executor/executor.go, internal/executor/executortest/executortest.go, internal/inspect/dependencies/renv/available_packages.go, internal/inspect/dependencies/renv/available_packages_test.go, internal/interpreters/r.go, internal/interpreters/r_interpreter_functional_test.go, internal/interpreters/r_test.go, internal/publish/r_functional_test.go, justfile
Added functional tests for calling into R from Windows (and particularly when R is installed by rig). Those confirmed the failure. Due to the [way quotes work in windows](https://learn.microsoft.com/en-gb/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way), when the R executable was a `.bat`, we needed to do more + different quoting than we already were for the scripts we shelled out to. This PR changes those to write the script portions out to files and then use `R... -f ...` to run them. This is more robust since we don't have to worry about quoting within the contents of the script.
Resolves #2598
_last sentence of intent_ …
=> Quote paths to support windows

CHANGELOG.md, extensions/vscode/CHANGELOG.md, internal/inspect/dependencies/renv/available_packages_test.go, internal/interpreters/python.go, internal/interpreters/r.go, internal/interpreters/r_mock.go, internal/publish/publish.go, internal/publish/publish_test.go, internal/services/api/post_deployment.go, internal/services/api/post_deployment_test.go, internal/services/api/post_inspect.go, internal/services/api/post_inspect_test.go
Fix inconsistent runtime discovery and selection when deploying from Positron.
Fixes #2648 #2663
The API deployment handler was taking into account the preferred runtime at the beginning but it was ignoring it after some initial validations.
Updated the necessary methods to make use of the preferred runtime across the complete deployment request.
Users should be able to deploy with the selected runtime in Positron.
Updated the related unit tests
Try deploying content from Positron, while selecting a different R or Python version and seeing the deployment go through with success.
=> fix(runtime): Fix inconsistent runtime discovery and selection when deploying from Positron

internal/credentials/credentials.go, internal/credentials/credentials_test.go, internal/credentials/errors.go, internal/credentials/keyring_test.go, internal/services/api/post_credentials.go
Currently we have checks in place to prevent users from creating new credentials for the same server URL. However, we want users to be able to create multiple credentials for Connect Cloud (but not with the same account). That means we have to compare both the credential URL and account instead of just the URL.
We'll also have to make changes in the extension code, which performs a similar validation.
Updated the `ConflictCheck` method to check AccountID in addition to URL.
none.
Added assertions for:
- When a user creates a duplicate cloud credential
- When a user creates a non-duplicate cloud credential with the same URL
Run the following curls:
```
curl -X POST …
```
=> check for existing credential by combination of URL and account name

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/webviews/homeView/package-lock.json, extensions/vscode/webviews/homeView/package.json
Upgrades `axios` to address a critical vulnerability with `form-data@4.0.2`: https://github.com/advisories/GHSA-fjxv-7rqg-78g4
=> Upgrade `axios` to `1.11.0`

test/.gitignore
Minor change to include some uv generated files in the `test/e2e` directory's `.gitignore` so if you use `uv` to manage your `venv` you don't have lingering files for git.
=> chore: Add uv files to test/e2e/.gitignore

CONTRIBUTING.md
Removes reference to internal docs site in our CONTRIBUTING doc.
=> docs: Remove reference to internal docs site

CHANGELOG.md, extensions/vscode/src/views/homeView.ts
This PR addresses a piece of feedback from @wch while working through an issue where the expectation was that the "Select Deployment" input would dismiss when focus changed similar to other VS Code inputs.
This PR only changes the "Select Deployment" quick pick since it doesn't have any user input we expect outside of VS Code (like we do for API keys in the Credential flow).
Part of #2358
Removed `quickPick.ignoreFocusOut = true;` so it defaults to `false`
Users can now dismiss the "Select Deployment" input by clicking away from it.
=> feat: Dismiss select deployment with focus out

internal/accounts/account_source.go, internal/accounts/account_source_test.go, internal/state/state.go, internal/state/state_test.go
This PR follows on the heels of https://github.com/posit-dev/publisher/pull/2789#pullrequestreview-3102130529, as it is cleaning up the dead code related to supporting environment variables as a credential.
To verify, I have run the normal building steps and then executed the existing e2e tests, which include validation for credential support. If CI passes, we should be good with the removal of this code.
=> chore: Remove remnents of credentials from environment variable support

internal/accounts/account.go, internal/clients/cloud_auth/oauth.go, internal/clients/connect_cloud/client_connect_cloud.go, internal/clients/connect_cloud/client_connect_cloud_test.go, internal/credentials/credentials.go, internal/credentials/credentials_test.go, internal/credentials/file.go, internal/credentials/file_test.go, internal/credentials/keyring_test.go, internal/publish/publish_test.go, internal/services/api/get_connect_cloud_accounts.go, internal/services/api/get_connect_cloud_accounts_test.go, internal/services/api/post_connect_cloud_oauth_token.go, internal/services/api/post_credentials.go, internal/types/cloud.go
We ended up sending `Bearer Bearer` in the Authorization header again, I think as a result of a bad merge. This PR fixes that, and also includes a refactor to make types more meaningful.
bug fix for Connect Cloud paths.
Fixes automated tests to expect the correct data.
Initiate a deploy using an existing credential - previously this would error with a 401.
=> Fix Authorization header for Connect Cloud API client

CHANGELOG.md, extensions/vscode/src/views/logs.ts
This PR introduces theme colors for the Log Stage Statuses in the Publisher Logs view.
[VS Code's theme color's for testing](https://code.visualstudio.com/api/references/theme-color#testing-colors) were utilized since there we colors available for each of the statuses we were trying to communicate already - queued, skipped, success, and errored.
<details>
</details> 
Resolves #2382
Nice and straightforward approach, passed the `ThemeColor` in the `ThemeIcon` constructor.
Users will see color based on their selected theme in the Publisher logs making it easier to see things like errors.
Publish forcing an error to see an error state in the …
=> feat: Add theme colors to Publisher logs

internal/credentials/credentials.go, internal/credentials/credentials_test.go, internal/credentials/keyring.go, internal/credentials/keyring_legacy.go, internal/credentials/keyring_test.go
Resolves #2783
Instead of storing all of the credentials in one keyring item, store each in it's own keyring item. This does mean that we need to have a separate keyring item that is a list of known items (the go-keyring package does not seem to have the ability to list and parse names of keyring items, you must get them by name).
Mostly Claude
Be able to store more credentials (and more than _one_ legacy token-based auth method)
Added some tests, especially for the migration
TODO:
=> First pass at multiple keyring support

.github/actions/setup/action.yaml, .github/workflows/agent.yaml, .github/workflows/archive.yaml, .github/workflows/build.yaml, .github/workflows/cleanup.yaml, .github/workflows/contract-deps.yaml, .github/workflows/e2e.yaml, .github/workflows/home-view-unit-test.yaml, .github/workflows/lint.yaml, .github/workflows/package.yaml, .github/workflows/publish.yaml, .github/workflows/release.yaml, .github/workflows/upload.yaml, .github/workflows/vscode.yaml
Upgrades the GitHub actions we use in various workflows.
Specifically:
- [`extractions/setup-just`](https://github.com/extractions/setup-just) now at `v3`
- [`actions/checkout`](https://github.com/actions/checkout) now at `v5`
- [`actions/download-artifact`](https://github.com/actions/download-artifact) now at `v5`
- Looking at [the release notes](https://github.com/actions/download-artifact/releases/tag/v5.0.0) we did not need to worry about the breaking changes since we already download artifacts by `name`
=> chore: upgrade github action versions

extensions/vscode/src/api/types/events.ts, internal/publish/connect_cloud/publish_to_server.go, internal/services/api/post_deployment.go
Resolves #2853 
The intent of this PR is to make the new events for publishing to Connect Cloud visible in the event progress pop-up in the bottom right corner of the editor as the publishing happens.
The actual root cause of the bug was a legitimate change in the order of events for publishing. What was happening was:
- Event A starts - displays active event label for event A
- Event B starts - displays active event label for event B (hides active label for event A)
- Event B ends - displays inactive event label for event B
- Event A continues to happen sending log events while displaying the inactive event label for event B 
- ...
- Event A ends - event progress box …
=> Fixing the events for Connect Cloud publishing

extensions/vscode/package.json, extensions/vscode/src/extension.ts, extensions/vscode/src/types/messages/webviewToHostMessages.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
Resolves #2686 
Resolves #2907 
The intent here is to hide Connect functionality that won't be supported for Connect Cloud at the moment. Said functionality in this case refers to the "associate deployment to existing content" functionality.
I have conditionally hidden the unsupported functionality for Connect Cloud using the `serverType` to figure out the product type to hide the unsupported functionality for Connect Cloud.
None.
E2E tests pass on CI for this branch.
=> Hiding the associate deployment to existing content functionality for Connect Cloud

CHANGELOG.md, extensions/vscode/src/views/logs.ts
This PR introduces a new feature: when the "posit-publisher-logs" panel `TreeView` is revealed the first failing deployment stage (if one exists) will be revealed.
Revealing it:
- scrolls it into view
- expands other `TreeViewItems` if necessary
- expands the `LogsTreeStageItem` itself
Resolves #2857 #2858
The approach was to use the [TreeView `reveal()` method](https://code.visualstudio.com/api/references/vscode-api#TreeView.reveal) alongside an [`onDidChangeVisibility` listener](https://code.visualstudio.com/api/references/vscode-api#TreeView.onDidChangeVisibility) on the TreeView.
When the TreeView is shown we try to grab the first `LogsTreeStageItem` has the …
=> feat: Revealing first failing stage in Publisher logs

extensions/vscode/src/api/types/events.ts, extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/views/homeView.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/DeployButton.vue, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/stores/home.ts, test/e2e/tests/error-err-config.cy.js
Resolves #2871
Resolves #2864 
Resolves #2870 
The intent of this PR is to fix the bugs listed above and add a small feature enhancement to show more detailed errors above the "Deploy Your Project" button.
The approach to add the detailed errors was simply expose the data since it was already available to us. The more complex bug fix was to stop the user from triggering multiple deployments. This was accomplished by introducing a new stream event that triggers disabling/enabling the deploy button accordingly.
It would probably be helpful to review this PR by commits to see all the 3 separate fixes/enhancements.
Only good things:
- No more triggering multiple deployments …
=> Multiple bug fixes and feature enhancement for the publisher extension

extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/views/deployProgress.ts, extensions/vscode/src/views/logs.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
Resolves #2873 
The intent of this PR is to tweak the wording on the cancel deploy info message and button labeling so it is more obvious that:
- Clicking the button will just open the publisher logs panel (if it isn't already opened) in your editor.
- The deployment "may" or "may not" continue in the server when cancelled depending on how fast the cancel button was clicked. At least this is the case for Connect Cloud where if you click the button fast enough, the publish won't happen in the server at all.
The approach to the wording and labeling changes were simple enough. However, while trying out the deployment cancelling I did find a case where the "Deploy Your …
=> Tweaking the wording on the cancel deploy info message and some other minor fixes

extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue
Resolves #2932 
The intent of this PR is to adjust the missing credential message to the product type.
- Connect: "No credential was found for the deployment's server."
- Connect Cloud: "No credential was found for the deployment's account."
Simple approach, determine the product based on the server type and adjust the message accordingly.
The user will see a more accurate message for missing credentials of Connect Cloud deployments.
E2E tests pass on CI for this branch.
=> Fixing the missing credential message on the homeView

CHANGELOG.md, extensions/vscode/src/multiStepInputs/newConnectCredential.ts
When creating a Connect credential we ask the user to input their server URL.
This PR changes that making the default value to the hostname of the URL they gave us in the earlier input step to reduce the amount of user input necessary.
Resolves #2922
Grabbed the `url` from the `MultiStepState` and attempt to URL parse it to grab the `url.hostname`.
If that parsing doesn't work fallback to the current behavior where there isn't a default.
Reduces friction when creating a Connect credential by reducing user input.
Create a Connect Credential and see the default value filled in for the name!
=> feat: Use hostname as initial credential name

extensions/vscode/src/multiStepInputs/newDeployment.ts, extensions/vscode/src/types/shared.ts, extensions/vscode/src/views/homeView.ts
Resolves #2939 
The intent of this PR is to refresh the credential list in the homeView when creating a new deployment failed but creating a new credential succeeded.
To avoid forcing a credential refresh regardless of having created a new credential or not while creating a new deployment, I have changed the return type of `newDeployment()` to always return an object that may contain undefined properties for all things needed for creating a new deployment. The approach was to declare a new deployment creation successful only when all properties are present, otherwise, check the credential property to trigger a credential refresh only if necessary.
The user will see …
=> Refreshing the credentials when creating a new deployment failed but creating a new credential succeeded

CHANGELOG.md, extensions/vscode/package.json, extensions/vscode/src/extension.ts
This PR sets the default of the auto opening logs when there is a deployment failure to `true`.
This has been turned on for user testing purposes. Depending on that feedback, we will make changes to the default.
=> feat: set default for auto open logs on failure to true

CHANGELOG.md, docs/installation.md, extensions/vscode/CHANGELOG.md, install-publisher.bash
Setup for `1.19.0` pre-release. Since this uses an odd number for the minor part of `major.minor.patch` it will be a pre-release version.
Users setup for pre-release versions will be updated to this version.
=> Setup release 1.19.0

extensions/vscode/src/api/types/configurations.ts, extensions/vscode/src/multiStepInputs/newDeployment.ts, internal/inspect/detectors/quarto.go, internal/inspect/detectors/quarto_inspect_output.go, internal/inspect/detectors/quarto_test.go
Introducing necessary changes to prompt the user with option to deploy Quarto rendered doc.
<details>
<summary>Prompt Screenshot</summary>
</details>
Resolves #2849
Detect if there is existing configuration alternatives within the Quarto configurations detected in the extension code when creating a new deployment and offer the option to the user.
Users now will be offered the option to publish the rendered version of documents that Quarto can handle, that is, aside from `.qmd` files, `.Rmd` documents and Jupyter `.ipynb` notebooks that Quarto can render will also present the option to publish the rendered result.
Since the option to publish the renderings requires …
=> Prompt the user with option to deploy Quarto rendered doc

CHANGELOG.md, docs/configuration.md, docs/vscode.md, internal/config/types.go, internal/publish/publish.go, internal/publish/r_package_descriptions.go, internal/publish/r_package_descriptions_test.go, internal/schema/schemas/draft/posit-publishing-schema-v3.json, internal/schema/schemas/posit-publishing-schema-v3.json
This turns on the support for generating project dependencies directly from the `renv.lock` file without the need for an existing library. This is a step in https://github.com/posit-dev/publisher/issues/2838 to improve user experience when deploying R projects that leverages previously built blocks.
Support for generating manifest packages from `renv.lock` was already implemented in https://github.com/posit-dev/publisher/issues/2773 this PR enables that by default and provides an option to switch it back.
Log messages were added to the deploy process to inform the user of how the packages were detected.
Projects providing a `renv.lock` will no longer need the local library to be in sync with the lockfile.
Tests to verify packages retrieval with both old and new …
=> feat: Generate project dependencies from renv.lock during deploy

CHANGELOG.md, extensions/vscode/webviews/homeView/src/components/CodeCheckbox.vue, extensions/vscode/webviews/homeView/src/components/tree/TreeItemCheckbox.vue, extensions/vscode/webviews/homeView/src/main.ts
Replaces the `vscode-checkbox` with a custom `CodeCheckbox` component while maintaining nearly the same styling. 
The only styling difference is using the CSS variable `--vscode-settings-checkboxForeground` which we weren't before. This will make our checkboxes look a little more native.
<details>
<summary>Side by Side</summary>
</details> 
<details>
</details> 
With the new component I wasn't able to reproduce #2793.
Resolves #2793
Part of #2156
The approach here was to use the MIT licensed [VSCode Elements Lite Checkbox](https://vscode-elements.github.io/elements-lite/components/checkbox/configurator/) as a starting point.
There was no …
=> feat: create CodeCheckbox component

extensions/vscode/src/multiStepInputs/newDeployment.ts
Re-arrange `inputConfigAlternatives` deployment step so the chosen inspection result check is not hardcoded
Check the `inspectResult` configuration type and do not rely on label strings.
Choosing to publish the rendered version of a Quarto doc should still work.
=> feat: Re-arrange inputConfigAlternatives deployment step so the chosen inspection result check is not hardcoded

CHANGELOG.md, internal/publish/manifest.go, internal/publish/manifest_test.go, internal/publish/publish_test.go
As part of https://github.com/posit-dev/publisher/issues/2838 this adds the step where the previously implemented dependencies scanning utilities are actually used when the project doesn't provide an renv.lock file.
The function generating the manifest will now check if a lockfile exists, if it doesn't it will ask `getRPackages` to scan for dependencies.
Users should no longer need to create an renv to be able to deploy projects.
There are 4 tests checking for the various combination of cases, the two case where scanning is triggered are
- A lockfile was configured but doesn't exist
- A lockfile was not configured and it doesn't exist
=> feat: Add automatic detection of dependencies when no renv.lock file exists

extensions/vscode/src/api/types/configurations.ts, internal/config/types.go, internal/inspect/detectors/quarto.go, internal/inspect/detectors/quarto_test.go, internal/schema/schemas/draft/posit-publishing-schema-v3.json, internal/schema/schemas/posit-publishing-schema-v3.json
Related to #2948 
Include a new `source` field for resulting deployment configurations of type `"html"` that are generated as alternative deployments for Quarto projects.
This to allow an upcoming `"Render"` button to render the project on demand, with the `source` field acting as the association link between the resulting `html` files and an original renderable project.
Update configuration objects, schemas and include this new field on Quarto alternative `html` configurations.
When creating a new deployment for a Quarto project and selecting the "Publish rendered document only" option, the `source` field will be included in the resulting configuration. Aside from …
=> feat: Include source field on static content configurations generated by Quarto projects

internal/inspect/detectors/quarto.go, internal/inspect/detectors/quarto_test.go
Resolves #2890 
Getting a configuration with `type= "unknown"` is painful. Users that do not have a Quarto binary on the system but that the project can be easily identified as a Quarto project by `.qmd` files are landing in this state.
This PR aims to fix that.
If there is no Quarto binary on the system, pay attention to the files so that for `.qmd` files or if there is a `_quarto.yml` present we determine the project is a Quarto project.
The resulting configuration will add the adjacent `.qmd` files, we cannot do more than that since `quarto inspect` won;t work. Even so, it is a much better state that can be fixed with the files picker, rather than having `type= …
=> feat: Prevent users to have unknown content configurations for Quarto projects

CHANGELOG.md, extensions/vscode/src/types/messages/hostToWebviewMessages.ts, extensions/vscode/src/views/renders.test.ts, extensions/vscode/src/views/renders.ts, extensions/vscode/webviews/homeView/src/HostConduitService.ts, extensions/vscode/webviews/homeView/src/components/DeployButton.vue, extensions/vscode/webviews/homeView/src/components/EvenEasierDeploy.vue, extensions/vscode/webviews/homeView/src/components/ProcessProgress.vue, extensions/vscode/webviews/homeView/src/components/ProcessSummary.vue, extensions/vscode/webviews/homeView/src/components/RenderButton.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
Resolves #2940 
This PR aims to communicate more prominently the result of the rendering.
- Render was successful
- Render failed
<details>
<summary>
Screenshots
</summary>
**Rendering content**
---
**Successful render**
---
**Render failed**
</details>
- Create two new components to handle the messaging (pulled out from `EvenEasierDeploy`), `<ProcessSummary>` and `<ProcessProgress>`
- Enhance the render events between `host <-> view` to communicate more details of the render process and use the new components to display such status.
User will have more prominent messaging about the end result of rendering Quarto projects.
Added and updated unit tests
For Quarto …
=> feat(rendering): More prominent Quarto rendering status messaging

CHANGELOG.md, extensions/vscode/webviews/homeView/src/components/views/RPackages.vue, extensions/vscode/webviews/homeView/src/stores/home.ts
Remove alert icon from R Packages header that showed when there was no `renv` infrastructure.
Remove the alert from `RPackages.vue` and `home.ts`.
As far as I can tell, no automated tests cover this alert.
- Run the extension in an R project which isn't using `renv`, confirm there is no alert icon in the R Packages header.
=> remove alert from R Packges header

test/sample-content/gradio/requirements.txt
Addresses some dependabot vulnerability scans without impacting our ability to publish `sample-content/gradio`
=> chore: unpin gradio dependency in `sample-content/gradio`

CHANGELOG.md, extensions/vscode/src/api/index.ts, extensions/vscode/src/api/resources/ContentRecords.ts, extensions/vscode/src/api/resources/Packages.ts, extensions/vscode/src/api/resources/RepoOptionsForwarding.test.ts, extensions/vscode/src/api/types/positron.ts, extensions/vscode/src/utils/positronSettings.ts, extensions/vscode/src/views/homeView.ts, internal/clients/connect/client_connect.go, internal/clients/connect/mock_client.go, internal/inspect/dependencies/renv/manifest_packages.go, internal/inspect/dependencies/renv/manifest_packages_from_lockfile.go, internal/inspect/dependencies/renv/manifest_packages_from_lockfile_test.go, internal/inspect/dependencies/renv/manifest_packages_test.go, internal/inspect/dependencies/renv/project_dependencies.go, internal/inspect/dependencies/renv/project_dependencies_functional_test.go, internal/inspect/dependencies/renv/project_dependencies_test.go, internal/publish/manifest.go, internal/publish/publish.go, internal/publish/publish_test.go, internal/publish/r_functional_test.go, internal/services/api/positron_helpers.go, internal/services/api/positron_settings.go, internal/services/api/post_deployment.go, internal/services/api/post_deployment_test.go, internal/services/api/post_packages_r_scan.go, internal/state/state.go, internal/state/state_test.go
Make sure that `renv.lock` files generated by the publisher to use the default repositories set by Positron options.
Closes https://github.com/posit-dev/publisher/issues/3038
Read the options from the VSCode extension and submit them to the API for scanning dependencies and performing deploys.
Users that use Positron should see faster deploy of packages as they can rely on ppm providing binary packages.
* Added tests to confirm that repoOptions are used when generating a new renv.lock
* Added tests to confirm that UI does submit the options to the backend.
=> feat: Use Positron configured repositories if available.

CHANGELOG.md, internal/inspect/dependencies/renv/lockfile.go, internal/inspect/dependencies/renv/manifest_packages.go, internal/inspect/dependencies/renv/manifest_packages_from_lockfile.go, internal/inspect/dependencies/renv/manifest_packages_from_lockfile_test.go
Closes #3147
When loading the lockfile, the `Remote*` fields are now loaded and when generating the `manifest.json` those are added to the `Description` of the package.
Should fix the reported error:
```
Hi all - i'm trying to publish to Connect using a dev version of pins. I installed it using pak::pak("rstudio/pins-r") but i'm hitting this error when publishing:
```
There is a test verifying that the generated manifest does indeed have the fields.
The implementation is based on https://github.com/rstudio/packrat/blob/b3127db3cea2144b1e3bd9c17de1da277b4776e9/R/github.R#L72-L98
Which confirms that `Remote*` fields are all we should need.
=> fix: add support for Remote* fields in lockfile

extensions/vscode/package.json, extensions/vscode/src/extension.ts, extensions/vscode/src/llm/index.ts, extensions/vscode/src/llm/tooling/troubleshoot/publishFailureTroubleshootTool.ts, extensions/vscode/src/views/logs.ts
Resolves #3157 
LLM tool to allow Assistants to access the deployment logs for troubleshooting.
<details>
<summary>Screencapture - Troubleshooting deployment failure with Positron Assistant</summary>
https://github.com/user-attachments/assets/2de54560-7905-49a7-ac4f-04cb0e14f640
</details>
- Create and register the new troubleshooting tool when the Publisher extension is activated.
- Import and use the existing logs service provider `LogsViewProvider` to be used by this tool.
- Users can call the tool directly, `#troubleshootDeploymentFailure`, when working with an LLM.
- When in agent mode, this tool does not need to be referenced directly, asking "Why my deployment …
=> feat(llm-tooling): troubleshootDeploymentFailure - Get and use deployment logs to troubleshoot the publishing failure

extensions/vscode/CONTRIBUTING.md
Adds a note to CONTRIBUTING.md about the need to separately set up the `code` CLI tool. I bumped into this because I didn't have it set up, so `just install` failed.
=> chore: add note about needing to set up code cli
